lib/logger.js
test/config/validator.js
test/logger.js

... also added the `recommendation` method, which we will use in #101.

Adding tests for the logger and cleaning up a bit internally

---

README.md

It can be really handy to rapidly check if an upcoming version has been released or not.

Add badge telling current npm version

---

fixtures/js/hello_world.mjs
lib/config-generator.js
test/functional.js

updating resolve.extensions to include webpack4 default extensions

---

lib/plugins/optimize-css-assets.js
test/functional.js

Conditionally add some logic to prevent accidental sourcemaps

---

package.json
yarn.lock

* Fixes #480
* See https://www.npmjs.com/advisories/725

Upgrade webpack-dev-server (security)

---

.travis.yml
package.json
test/functional.js
yarn.lock

Just something to do occasionally. This does not affect users, and our test suite already takes over and tests high and low deps.

[Chore] Bumping yarn.lock deps

---

package.json
yarn.lock

url-loader can be installed in version 1 and 2 #596

---

package.json
yarn.lock

Upgrade yargs-parser

---

lib/WebpackConfig.js

Introduced in #738 - @jdreesen I think this was just a typo? Can you confirm that my PR is right?
Thanks!

Fixing babel.config.js filename in message

---

package.json
test/package-helper.js
yarn.lock

Resolves #797 
Tests: ✔️ [Node 10](https://github.com/skmedix/webpack-encore/runs/841902641?check_suite_focus=true) | ✔️ [Node 12](https://github.com/skmedix/webpack-encore/runs/841902662?check_suite_focus=true)

⬆️ Upgraded sass-loader to ^9.0.1

---

package.json
yarn.lock

Update assets-webpack-plugin to ^5.1.1

---

package.json
yarn.lock

See https://github.com/bholloway/resolve-url-loader/issues/170 and https://npmjs.com/advisories/1573

Update resolve-url-loader to fix prototype pollution

---

package.json
yarn.lock

postcss-loader is a full major version behind, this updates it to v4

Updates postcss loader to v4

---

package.json
test/package-helper.js
yarn.lock

Bump sass-loader to ^10.0.0 

---

index.js

adding docs related to disabling the css extraction and the dev-server

---

yarn.lock

Just a chore - doesn't affect end-users

bumping all dependencies

---

CHANGELOG.md

Previous CL entries will be updated to the new format at a later time.

[release] build changelog for 1.5.0

---

package.json
yarn.lock

fixes failing lowest depends in PR #1034

[dependencies] drop Typescript < 3.7.2

---

test/config-generator.js

Tidying up fixes for preact

---

CHANGELOG.md

Re-sync changelog

---

.github/workflows/high-depends.yml
.github/workflows/lint.yaml
.github/workflows/low-depends.yml
.github/workflows/stable-tests.yml
.github/workflows/testing_apps.yml
CHANGELOG.md

Some maintenance... close #1291

Upgrade GitHub Actions in CI

---

lib/loaders/css.js
lib/loaders/handlebars.js
lib/loaders/less.js
lib/loaders/sass.js
lib/loaders/stylus.js
lib/loaders/typescript.js
lib/loaders/vue.js
lib/plugins/notifier.js
lib/plugins/vue.js
lib/webpack/copy-files-loader.js
package.json

Those lines don't report such error.

Remove useless eslint disabling comments

---

lib/WebpackConfig.js

| Bug fix?      | yes/no
| New feature?  | yes/no 
| Deprecations? | yes/no 

Fix method name

---

package.json
test_apps/npm-with-babel/package-lock.json
test_apps/npm-with-external-babel-config/package-lock.json
test_apps/npm/package-lock.json
test_apps/pnpm-with-babel/pnpm-lock.yaml
test_apps/pnpm-with-external-babel-config/pnpm-lock.yaml
test_apps/pnpm/pnpm-lock.yaml
test_apps/yarn-pnp-with-babel/yarn.lock
test_apps/yarn-pnp-with-external-babel-config/yarn.lock
test_apps/yarn-pnp/yarn.lock
yarn.lock

| New feature?  | no 
Purely internal, it won't impact end-users (except for suggesting a newer version of `webpack-dev-server`). That's mainly to close issues opened in https://github.com/symfony/webpack-encore/security/dependabot

Upgrading some dependencies with vulnerability issues

---

.github/workflows/high-depends.yml
.github/workflows/low-depends.yml
.github/workflows/stable-tests.yml

| Issues        | Fix #1323 
Let's ensure Webpack Encore supports Node.js 23

Add support for Node.js 23

---

lib/WebpackConfig.js

| Bug fix?      | yes
| New feature?  | no 
| Issues        | Fix #886  

Remove warning for usage of configureLoaderRule

---

CHANGELOG.md
package.json
yarn.lock

Add support for babel-loader ^10.0.0

---

CHANGELOG.md
package.json
yarn.lock

Add support for style-loader ^4.0.0
