symfony/webpack-encore

lib/config-generator.js, test/config-generator.js, test/functional.js
The previous spot is an outdated spot anyways, and it caused an edge-case bug with
resolution of some SASS paths: https://github.com/symfony/symfony-demo/pull/586
=> Moving minification options

lib/WebpackConfig.js
When using webpack it's common to also provide window.jQuery because some libraries use it this way.
=> Add window.jquery to autoProvidejQuery()

bin/encore.js, lib/WebpackConfig.js, lib/config-generator.js, lib/config/RuntimeConfig.js, lib/config/parse-runtime.js, test/config/parse-runtime.js
This PR is a patch to provide simply add HMR support if the webpack-dev-server is use.
Sorry I don't know if there is a standard for PR on this repo.
To test, run `.node_modules/.bin/encore dev-server` and refresh the page of your project, then open the console and you should see `[WDS] Hot Module Replacement enabled.`
I think I can find a way to test it with the test suite.
=> Adding Hot Module Replacement support

lib/config-generator.js
https://github.com/webpack-contrib/style-loader/issues/18#issuecomment-56308183
We're enforcing that --hot is passed at the command line, which enables this plugin for you.
=> Removing duplicate HotModuleReplacementPlugin()

lib/config-generator.js
To give some feedback, we currently output this message after a build:
> 23 files written to web/build
But, that doesn't make sense when using the dev-server (as nothing - except `manifest.json` - is actually written). webpack-dev-server itself already renders helpful information about what address the server is running on, etc - we don't need to add that ourselves.
=> hide the 'Assets output' message when using the dev-server

lib/config-generator.js, lib/test/setup.js, test/functional.js
Really... a minor thing, but this is a better behavior.
=> When using the "clean" option, empty the dir, but don't remove it entirely

appveyor.yml
Added a configuration file for AppVeyor tried to mimic how it was defined in travis configuration file.
This is first time for me using AppVeyor so it defiantly need some more experienced eyes.
=> Add appveyor configuration file

index.js, lib/WebpackConfig.js, lib/config-generator.js, test/WebpackConfig.js, test/config-generator.js
Currently Encore only supports specific loaders, and adding additional loaders is not very intuitive and adds additional (ugly) code to the config, E.G we are using handlebars with the [handlebars-loader](https://github.com/pcardune/handlebars-loader) and have to manually add the loader to the config:
```js
var webpackConfig = Encore.getWebpackConfig();
webpackConfig.module.rules.push({ test: /\.hbs$/, loader: 'handlebars-loader' });
```
So I propose allowing to add custom loaders through a simple `addLoader(test, loader)` function.
This changes the above code to the following:
```js
// ...
.addLoader(/\.hbs$/, 'handlebars-loader')
```
It is also possible to set custom config for the loaders by passing an object instead of a string:
```js
// ...
.addLoader(/\.hbs$/, { 'loader': …
```
=> Allow to add custom loaders

lib/WebpackConfig.js, lib/config/parse-runtime.js, package.json, test/WebpackConfig.js, test/config/parse-runtime.js, yarn.lock
In babel-loader 7.1, they added a new argument to `resolve-rc`. This updates Encore to require 7.1 and pass in that new argument.
Of course, the underlying problem is that we're relying on an internal function - so it's entirely valid for them to break BC. We should obviously minimize doing this, but I still think it's a good idea: I don't want to try to re-implement their logic. For example, there are now 2 new places where you can store the Babel configuration... and by using `resolve-rc`, we're now checking for those automatically.
=> Forcing babel-loader 7.1 and updating resolve-rc for new argument

index.js, lib/WebpackConfig.js, lib/config-generator.js, test/WebpackConfig.js, test/config-generator.js
Encore does not support adding an extra plugin to the list of registered plugins.
In Symfony demo, we try to reduce the size of one of our entries and have to manually add the plugin to the config by doing this : 
```js
var config = Encore.getWebpackConfig();
config.plugins.push(new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/));
```
I propose to update the API of Encore through a new method `addPlugin(plugin)`.
```js
Encore
// ...
.addPlugin(new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/))
```
=> Allow to add extra plugin

lib/config-generator.js, lib/config/path-util.js, lib/config/validator.js, lib/webpack/webpack-manifest-plugin.js, test/config-generator.js, test/config/path-util.js, test/config/validator.js, test/functional.js
In a few places, we rely (relied) on doing some "string replace" on paths. Obviously, that doesn't play well with the windows `\` directory separators. This fixes the few places that rely on this and includes tests that exposed those failures on AppVeyor.
=> Fixing Windows Support

lib/WebpackConfig.js
Fixes #32 
This is because - when this is enabled - it's impossible to expose jQuery as a global
variable on window (without use the expose loader). Specifically, window.jQuery = ...
is re-written in your JS code.
A docs PR also needs to be opened to document how to fix problems if a library depends on `window.jQuery` specifically (is there a good re-world example?)
=> Removing window.jQuery from autoProvidejQuery

lib/WebpackConfig.js
By adding `window.jQuery` to `autoProvidejQuery()`, it caused problems by making `window.jQuery = require('jquery')` not work (#32). But, *not* having it causes other obvious problems (see #52).
This re-adds `window.jQuery` back. As a fix, we would document exposing jQuery as a global variable by doing this:
```js
global.$ = global.jQuery = require('jquery');
```
ping @alOneh
=> Re-adding window.jQuery to autoProvidejQuery

index.js, package.json
This fix #62 and adds index.js to lint task to avoid such things in future.
Missing comma is related to #50. I believe the merge remove it by accident.
=> Fix missing comma and lint index

index.js, lib/WebpackConfig.js, test/WebpackConfig.js
The `enableTypeScriptLoader()` should allow for no callback function - it's probably not needed in most cases.
Ping @davidmpaz
=> Making enableTypeScriptLoader() options callback optional

CHANGELOG.md, index.js, lib/WebpackConfig.js, lib/loaders/sass.js, test/WebpackConfig.js, test/loaders/sass.js
Fixes #14 
This is a BC break, which I want to minimize. But, since we're pre 1.0, BC breaks are allowed. And this will fail clearly the first time you try to run encore.
Docs: https://github.com/symfony/symfony-docs/pull/8108
=> Adding ability to pass options to sass-loader

index.js
=> Allow resetting the state of the Encore singleton

lib/loaders/vue.js, test/functional.js
Prior to this fix when the less loader isn't enabled, the scss loader config is rewritten by mistake, leading to this error:
> Module build failed: Error: Cannot process lang="less" inside src/js/Player.vue: the less-loader is not activated.
I also fix a functional test case for Vue.js. Actually, the tests check if the first error thrown by webpack is about missing less loader. But the fixtures needs these loaders in the following order: scss, sass and finally less. Since there's no other loader than the VueJs one loaded in this test case, errors should be in the same order.
=> Fix inability to use scss loader with Vue.js

bin/encore.js, index.js, lib/WebpackConfig.js, lib/config-generator.js, lib/config/RuntimeConfig.js, lib/config/parse-runtime.js, lib/config/validator.js, lib/logger.js, test/WebpackConfig.js, test/config-generator.js, test/config/parse-runtime.js, test/config/validator.js
Fixes #59 and finishes #66.
* Adds a new `--keep-public-path` option for `dev-server`. When used, your `publicPath` is not prefixed with the dev server URL. For #59, this means you can use `setPublicPath('/build')` with the dev-server, and your assets will remain local (i.e. `/build/main.js` instead of `http://localhost:8080/build/main.js`).
* It is now possible to pass an absolute URL to `setPublicPath()` without an error when using `dev-server`. But, we issue a big warning, because this means your assets will point to to that absolute URL, instead of to the dev-server (which for most setups, is not what you want).
@samjarrett I'd love to confirm that this would solve your issue in Docker :).
=> Relaxed public path requirements with dev-server

fixtures/css/imports_autoprefixer.css, lib/loaders/css.js, test/functional.js
Fixes #98
By default, when you use `@import`, loaders are not applied. This fixes that: using the postcss-loader when it's used. The functional test proves the fix.
=> Fixing a bug where @import CSS files were not put through the autoprexer

index.js, lib/WebpackConfig.js, lib/loaders/css.js, test/WebpackConfig.js, test/loaders/css.js
This PR allows to add a callback as the first argument of `Encore.enablePostCssLoader()` in order to be able to modify the options of the `postcss-loader`.
As an example (fixes #129):
```js
Encore.enablePostCssLoader((options) => {
options.config = {
path: 'app/config/postcss.config.js'
};
});
```
=> Add options callback to Encore.enablePostCssLoader()

test/WebpackConfig.js
This PR removes a duplicate test case in `WebpackConfig.js`:
* [first instance](https://github.com/symfony/webpack-encore/blob/v0.12.0/test/WebpackConfig.js#L335-L346)
* [second instance](https://github.com/symfony/webpack-encore/blob/v0.12.0/test/WebpackConfig.js#L368-L379)
=> Remove duplicate addPlugin test case

lib/config-generator.js, test/functional.js
This creates extra comments in the final .js files, to help debugging. This was a mistake when originally added - the logic was reversed.
Fixes #120
=> Reversing pathinfo logic to avoid extra comments

lib/loaders/babel.js
See https://github.com/symfony/webpack-encore/issues/100#issuecomment-316883728
It just makes adding a custom plugin a bit less error-prone for the user.
=> Initializing the plugins key on babel, so you can call babelConfig.plugins.push()

index.js, lib/WebpackConfig.js, lib/loaders/less.js, test/WebpackConfig.js, test/loaders/less.js
This PR allows to add a callback as the first argument of `Encore.enableLessLoader()` (fixes #118).
I didn't notice that one was missing too when working on #130.
Example :
```js
Encore.enableLessLoader((options) => {
options.relativeUrls = false;
});
```
=> Add options callback to Encore.enableLessLoader()

index.js, lib/WebpackConfig.js, lib/config-generator.js, lib/plugins/extract-text.js, test/WebpackConfig.js, test/config-generator.js, test/index.js
This PR adds the `Encore.configureFilenames()` method to the public API (fixes #125).
**Example:**
```js
Encore.configureFilenames({
js: '[name].[chunkhash].js',
css: '[name].[contenthash].css',
images: 'images/[name].[hash:8].[ext]',
fonts: 'fonts/[name].[hash:8].[ext]'
});
```
If one key is defined in the first parameter it will be used for the filenames of the related category.  
If it isn't the behavior will stay the same as before.
For now I kept the old naming strategies as the default values. We could eventually change that following the discussion in #136.
=> Add Encore.configureFilenames() method to the public API

lib/test/setup.js
This PR replaces `process.stdout.write` by an empty function when running webpack in each functional test (fixes #47).
It also sets the `silent` option of the Zombie.js browser to true to avoid displaying things like:
```
Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
```
The only "noisy" message left should be `DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead` since it is sent to stderr (should be fixed when alexindigo/webpack-chunk-hash#9 is released).
=> Intercept Webpack output during functional tests

lib/WebpackConfig.js, test/WebpackConfig.js
```js
Encore.setManifestKeyPrefix('/public/');
```
This is allowed, and will still be allowed. But after this PR, you will get a warning.
This is to help people from "tripping up" and accidentally changing their manifest key prefix from `public/` to `/public/` when calling `setManifestKeyPrefix()`. I thought this might cause issues, and it did in #96 - https://github.com/symfony/webpack-encore/pull/96#issuecomment-316871049
Cheers!
=> Warning when manifest key prefix starts with "/"

index.js, lib/WebpackConfig.js, lib/config-generator.js, lib/features.js, lib/loaders/babel.js, package.json, test/WebpackConfig.js, test/config-generator.js, test/functional.js, test/index.js, test/loaders/babel.js, yarn.lock
This PR adds a `enablePreactPreset()` method to the public API.
Basically it allows to use [Preact](https://github.com/developit/preact) (which is an alternative to react), optionally in conjunction with [`preact-compat`](https://github.com/developit/preact-compat) (which makes it possible to use the same code you would have in a React app).
It doesn't enable a babel preset per-se but it's still some kind of preset and it makes it consistent with the already existing `enableReactPreset()` method.
The method takes as an argument an option object that allows to enable/disable the use of `preact-compat`:
```js
// Without preact-compat (default)
// - Adds transform-react-jsx to the plugins used by babel
//   and configures it to wrap JSX into Preact h() calls
Encore.enablePreactPreset()
// …
```
=> Add Preact preset (with preact-compat support)

index.js, package.json, yarn.lock
This PR aims to improve the error message displayed when an user makes a typo in the name of one of the API methods he's trying to use.
Since pictures speak louder than words:
**Before**
**After**
Note that the error is triggered when trying to access the property, not when the method is called (since it doesn't exist), hence the "is not a recognized property" message. I'm aware that the use of the "property" word in it may not be ideal, but using "method" instead feels wrong too since we could theoretically have other things than methods in the API object.
=> Add a 'Did you mean ...' error message in case of an unrecognized API property

index.js, lib/WebpackConfig.js, lib/loaders/sass.js, lib/logger.js, test/WebpackConfig.js, test/loaders/sass.js, test/logger.js
This PR deprecates the `resolve_url_loader` option used by the `enableSassLoader` and replaces it by `resolveUrlLoader`.
This is done to be consistent with other methods that use camel-case instead of snake-case (see [#152](https://github.com/symfony/webpack-encore/pull/152#issuecomment-329266198)).
`resolve_url_loader` will still work for now but will display the following deprecation message:
=> Replace "resolve_url_loader" by "resolveUrlLoader"

lib/webpack/delete-unused-entries-js-plugin.js, test/functional.js
This PR fixes an error occuring when calling `addStyleEntry` and using a query string versioning strategy at the same time (closes #160).
Basically, the `delete-unused-entries` part that removes "fake" js files created by the `addStyleEntry` method would only pick filenames ending by `.js` which may not be the case at this point if the chunkhash is appened after the filename as a query string (e.g.: `[name].js?[chunkhash:16]`).
=> Fix JS query string versioning when using addStyleEntry

index.js, package.json, test/bin/encore.js, yarn.lock
This PR removes the "__esModule is not a recognized property" error that is currently displayed after importing Encore using an ES6 import through a `webpack.config.babel.js` file (fixes #166).
=> Fix "__esModule is not a recognized property" error

lib/webpack/delete-unused-entries-js-plugin.js, test/functional.js
This PR fixes `<entry>.js.map` files not being deleted after calling `addStyleEntry(...)` and `enableSourceMaps(true)` in production mode.
=> Fix temporary map files not being deleted in production mode

lib/plugins/define.js, test/plugins/define.js
This PR fixes #171 by adding an instance of the `DefinePlugin` to the generated Webpack config no matter what the current environment is.
=> Add an instance of DefinePlugin even in development mode

index.js, lib/WebpackConfig.js, lib/config-generator.js, lib/plugins/asset-output-display.js, lib/plugins/clean.js, lib/plugins/commons-chunks.js, lib/plugins/define.js, lib/plugins/delete-unused-entries.js, lib/plugins/extract-text.js, lib/plugins/forked-ts-types.js, lib/plugins/loader-options.js, lib/plugins/manifest.js, lib/plugins/plugin-priorities.js, lib/plugins/uglify.js, lib/plugins/variable-provider.js, lib/plugins/versioning.js, test/WebpackConfig.js, test/config-generator.js, test/plugins/clean.js, test/plugins/define.js, test/plugins/extract-text.js, test/plugins/forked-ts-types.js, test/plugins/loader-options.js, test/plugins/manifest.js, test/plugins/uglify.js
Following the discussion in #165 this PR adds a `priority` parameter to the `Encore.addPlugin()` method in order to allow people to choose where their custom plugins will be added in the generated Webpack config (fixes #163).
__Examples:__
```js
const Encore = require('@symfony/webpack-encore');
// Without setting the priority a plugin will be
// appended to the other plugins.
Encore.addPlugin(new CustomPlugin());
```
```js
const Encore = require('@symfony/webpack-encore');
// If two plugins need to be sorted relatively to
// eachother (CustomPluginB will be placed before
// CustomPluginA):
Encore
.addPlugin(new CustomPluginA(), 100);
.addPlugin(new CustomPluginB(), 50)
;
```
```js
const Encore = require('@symfony/webpack-encore');
const PluginPriorities = …
```
=> Add a priority parameter to the Encore.addPlugin() method

lib/config-generator.js
Due to the following lines a new ts-loader rule is currently being added everytime the Webpack config is generated (for instance by calling `Encore.getWebpackConfig()`):
https://github.com/symfony/webpack-encore/blob/c6057af7521594d9d76cfd072b1f2421591e4a3f/lib/config-generator.js#L196-L200
__Example:__
```js
// webpack.config.js
const Encore = require('@symfony/webpack-encore');
Encore
.setOutputPath('build')
.setPublicPath('/')
.addEntry('src/index.ts')
.enableTypeScriptLoader()
;
console.log(Encore.getWebpackConfig().module.rules.length); // => 5
console.log(Encore.getWebpackConfig().module.rules.length); // => 6
console.log(Encore.getWebpackConfig().module.rules.length); // => 7
```
=> Fix new ts-loader rule being added when getWebpackConfig is called

package.json, yarn.lock
Fixes #91 by using `webpack-chunk-hash@^0.5.0` instead of `webpack-chunk-hash@^0.4.0` ([caret ranges](https://yarnpkg.com/lang/en/docs/dependency-versions/#toc-caret-ranges) don't allow to change the first non-zero digit).
=> Upgrade webpack-chunk-hash dependency

index.js, lib/WebpackConfig.js, lib/config-generator.js, lib/features.js, lib/plugins/notifier.js, lib/plugins/plugin-priorities.js, package.json, test/WebpackConfig.js, test/index.js, test/plugins/notifier.js, yarn.lock
This PR adds an `enableBuildNotifications()` method to the public API in order to use the `webpack-notifier` plugin (closes #187):
```js
// With default options
Encore.enableBuildNotifications();
// Conditionally
Encore.enableBuildNotifications(!Encore.isProduction());
// With custom options
Encore.enableBuildNotifications(true, (options) => {
options.title = 'Foo';
});
```
The plugin is disabled by default and needs to be installed manually using `yarn add --dev webpack-notifier`.
=> Add Encore.enableBuildNotifications() method

bin/encore.js, lib/config-generator.js, lib/config/parse-runtime.js, test/bin/encore.js
This PR fixes #204 by detecting the `--json` and `-j` options and:
* removing some `console.log` calls
* removing the `FriendlyErrorsWebpackPlugin`
* Using default `stats` values
As said in [that comment](https://github.com/symfony/webpack-encore/issues/204#issuecomment-346950361) of the related issue the `--silent` option has to be used with `yarn run encore` or `yarn encore` and must be placed before the name of the script.
For instance:
```bash
./node_modules/.bin/encore production --json
yarn run --silent encore production  --json
yarn --silent encore production  --json
yarn run encore production --json
yarn encore production --json
yarn run encore production --silent --json
yarn encore production --silent --json
```
Edit: Forgot to add a test yesterday, should be good now :)
=> Fix output when using "--json" or "-j" option

lib/WebpackConfig.js, test/WebpackConfig.js
There are valid use cases for setting the publicPath to something not starting with a forward slash as discussed in #88 and #26 
Throwing an error and stopping compilation is overkill for this and beyond the remit of webpack encore, so I propose this PR where a warning is given to the user instead and the `setPublicPath` method falls in line with behaviour of `setManifestKeyPrefix`
=> Replace error throwing with logger warning when publicPath is not absolute

index.js
I fixed a typo in a comment (`/web/build` is not a relative path).
I fixed some comments in order to be coherent with symfony docs and with the output produced when setManifestKeyPrefix is missing but necessary (`Error: Cannot determine how to prefix the keys in manifest.json. Call Encore.setManifestKeyPrefix() to choose what path (e.g. build/) to use when building your manifes  t keys. This is happening because you passed an absolute URL to setPublicPath().`)
=> fixed some comments in order to be coherent with docs

index.js
Hello, I'm trying to address #151 with this PR.
I have an error in my tests:
```
Public API
setOutputPath
Error: Encore.configureRuntimeEnvironment is not a recognized property or method.
- index.js:942 Object.get
/home/florent/dev/opensource/webpack-encore/index.js:942:27
- index.js:17 Context.beforeEach
/home/florent/dev/opensource/webpack-encore/test/index.js:17:13
- runnable.js:348 callFn
[webpack-encore]/[mocha]/lib/runnable.js:348:21
- runnable.js:340 Hook.Runnable.run
[webpack-encore]/[mocha]/lib/runnable.js:340:7
- runner.js:309 next
[webpack-encore]/[mocha]/lib/runner.js:309:10
- runner.js:339 Immediate.<anonymous>
[webpack-encore]/[mocha]/lib/runner.js:339:5
- timers.js:789 runCallback
```
I'm looking into it but any advice would be welcome so that we all get a proper proxy and …
=> Updated Encore object to class for proxy typehinting

index.js
The `plugin` parameter is described as `{string}` but in fact we want to have instances of a Webpack plugin here. So I think we should use `object` here, which reflects the fact that all examples and known usages use an object there...
=> Fix 'plugin' typehint on Encore.addPlugin

lib/plugins/commons-chunks.js
What gets extracted in this chunk is not the manifest (which creates confusion with the webpack manifest which is a JSON file used by the backend code, i.e. the Symfony asset component); it is the webpack runtime.
This runtime indeed includes some information also present in the manifest (it contains the mapping for all dynamic chunks), but that's not all of it.
=> Update the description of the webpack runtime chunk

fixtures/js/shared_example.js, index.js, lib/WebpackConfig.js, lib/config-generator.js, lib/plugins/plugin-priorities.js, lib/plugins/shared-entry-concat.js, lib/webpack/shared-entry-concat-plugin.js, package.json, test/functional.js
There is currently on big problem with the Webpack 4 support (#324): `createSharedEntry()` no longer works as expected.
Suppose this config:
```js
.createSharedEntry('layout', './assets/layout');
```
Where `assets/layout.js` looks like this:
```js
// assets/layout.js
// jquery will be in the "shared" entry and not repeated in other entries
const $ = require('jquery');
console.log('this code will not run');
```
In Webpack 3, the `console.log()` code WOULD run. But, in Webpack 4, the final `layout.js` file simply contains the code for all of the modules... but unless someone actually *requires* them, their code is not executed. As a result, unless some other entry explicitly had `require('./assets/layout.js')`, the `console.log()` would never actually execute.
This, unfortunately, is a big …
=> A hacky attempt at supporting createSharedEntry() in Webpack 4

index.js, lib/WebpackConfig.js, lib/loaders/css.js, test/WebpackConfig.js, test/loaders/css.js
Disabling the URL handler can be handy for importing legacy CSS.
Fixes https://github.com/symfony/webpack-encore/issues/334
=> Add option to configure the CSS loader

lib/webpack/shared-entry-concat-plugin.js, test/functional.js
This PR fixes #352.
When source maps are enabled, the original shared entry file ends with a commented line.
This is an issue when the "_tmp_shared" entry is appended to it since its first line then becomes part of that comment.
=> Fix shared entry file when source maps are enabled

lib/config-generator.js
As noted by @stof in #217, the current implementation of `Encore.addAliases()` and `Encore.addExternals()` doesn't create a copy of the given objects before putting them in the generated Webpack config.
Since it can lead to some issues when calling `getWebpackConfig()` multiple times without resetting Encore (the same objects being shared between configs), this PR creates a copy of them before adding them to the final config.
=> Use a copy of the given aliases and externals in the generated config

package.json, yarn.lock
2 things in this PR
* `babel` has now an stable release
* For the npm scripts, You don't need to use the full path to the local binaries inside the node_modules. 
From [npm's doc](https://docs.npmjs.com/cli/run-script)
>  Any binaries provided by locally-installed dependencies can be used without the node_modules/.bin prefix
=> Babel upgrade.

bin/encore.js, test/bin/encore.js
The webpack-dev-server dose not know the --keep-public-path argument
and fails with an 'Unknown Argument' error if it is aplied.
So before webpack-encore hands over controle to webpack-cli/-dev-server it has to
remove arguments that only exist for webpack-encore.
=> Filter --keep-public-path from arguments (fixes #180)

.travis.yml, scripts/force-lowest-dependencies.js, test/package-helper.js
This PR adds two Travis jobs that allow to test the lowest and highest versions of all the dependencies (including the dev ones since the version ranges are used by the package helper).
I wasn't sure about the method to use for the lowest versions since we can't really guess them without calling the npm's registry API. So, if someone has a better idea... :)
Note that both jobs currently fail for the following reasons:
- Lowest versions: This isn't really an issue since it seems related to Webpack 4 for which we haven't released a version yet. We could increase the minimum version to match the one from the `yarn.lock` file before releasing.
- Highest versions: This is caused by the last version of the `mini-css-extract-plugin` (0.4.3) which doesn't seem to work well with the …
=> Add new Travis jobs to test lowest/highest versions of all the dependencies

lib/plugins/manifest.js
This PR should fix #413.
When using `--watch` the first build works fine (unless you're using a recent version of `mini-css-extract-plugin`... but that's another story :)), but the next ones don't include all the assets.
Based on a few tests I made it could be related to https://github.com/danethurber/webpack-manifest-plugin/issues/144 but that issue won't be fixed until the next major version of WebpackManifestPlugin (3.x).
Since the workaround (setting the `seed` option to `{}`) seems to be working fine I suggest that we add it to the default options that are passed to the plugin.
=> Fix entries disappearing from the manifest when using --watch

index.js, lib/WebpackConfig.js, lib/config-generator.js, test/WebpackConfig.js, test/config-generator.js
This PR closes #342 by allowing to configure the js/jsx loaders' exclude rule by using `configureBabel()`.
For instance:
```js
Encore.configureBabel(
() => {},
{ exclude: /foo/ }
);
```
Note that it doesn't change the default behavior that excludes `node_modules` and `bower_components`.
**Edit:**
Also adds an `include_node_modules` option to use the default `exclude` rule but only include some Node modules (can't be used if the `exclude` option is also set):
```js
Encore.configureBabel(
() => {},
{ include_node_modules: ['foo', 'bar', 'baz'] }
);
```
=> Allow to configure the JS exclude rules through configureBabel

lib/plugins/entry-files-manifest.js, test/functional.js
Following my comment in #418 this PR adds an `entrypoints` key in the `entrypoints.json` file instead of putting everything at the root. It also simplifies a bit the code of the `processOutput` function to avoid duplicated code.
For now it won't really matter (since it'll be the only key) but it will avoid using "magic" keys later on if we want to add additional data (such as the hashes of the referenced files).
I'll also open a PR in the `webpack-encore-bundle` repository.
=> Put current data under an "entrypoints" key in the entrypoints.json file

lib/plugins/entry-files-manifest.js
Hi guys!
Fixes #426 
Description in the comment
=> Fixing bug where a second rebuild would explode due to entrypoints.json processing

index.js
- add ./assets prefix to path
- add missing `{`
=> Improve `copyFiles` method examples

lib/config-generator.js, lib/plugins/shared-entry-concat.js, lib/webpack/shared-entry-concat-plugin.js, package.json
=> Appending the _tmp_shared contents via an earlier hook

lib/plugins/entry-files-manifest.js
Fixes #450 
To be consistent with manifest.json, and because this is read by your server, so file size is not an issue.
=> pretty-printing entrypoints.json

lib/plugins/entry-files-manifest.js, test/functional.js
Fixes #452 
When `entrypoints.json` was originally designed, the values were made so that they matched the *keys* of `manifest.json` - the idea was that you would use both to get the final path. But later (before 0.21.0 releaser), we/I changed `entrypoints.json` so that the value is the final path - to avoid needing to do another lookup in `manifest.json`.
However, there was one piece that I missed when changing this: the opening `/` is currently being stripped off the values in `entrypoints.json`. This breaks subdirectory installs (see #452).
For most Symfony users, you won't notice this change.
**Current behavior**: The value is read from `entrypoints.json` (`build/foo.js`), then it is also found in `manifest.json` (via the `json_manifest_strategy`) and becomes `/build/foo.js`.
**New …
=> [BC Break] Fixing a bug where the entrypoint path opening slash was stripped

lib/config-generator.js, test/config-generator.js, test/functional.js
Fixes #461 
But, this does not expose the entry names internally in the code (as these are used instead of auto-incremet ids). I don't think there's a way around that.
Also, I'm still tracking down a somewhat related but that causes a related issue (meaningless id's changing in generated code) under very specific conditions. In fact, you can see it in this test case just by changing all the 3 of the entries to an array - e.g. 
```js
config.addEntry('main1', ['./js/code_splitting']);
if (includeExtraEntry) {
config.addEntry('main2', ['./js/eslint']);
}
config.addEntry('main3', ['./js/no_require']);
```
That doesn't need to block this PR, but I need to figure out the issue (it's Webpack behavior) and see if it affects versioning (i.e. if the contents change but the file hashes do NOT …
=> Always used named chunks AND prevent split chunks from changing too often.

lib/config-generator.js, test/functional.js
This PR adds a warning when `copyFiles()` is called with a `from` value that isn't an existing directory.
This is kind of related to #445 but even if the friendly-errors-webpack-plugin worked properly in this case the origin of the error would probably not be obvious (it'd most likely contain a reference to the temporary entry).
=> Display a warning when calling "copyFiles" with an invalid path

index.js, lib/WebpackConfig.js
Hi,
This PR adds two new methods `isDev()` and `isDevServer()` aside the already existing `isProduction()` method.
On a project at work, we should configure webpack-encore only when we are running the dev-server. 
There is the property `runtimeConfig.useDevServer` but we don't have access to `runtimeConfig` in our `webpack.config.js`.
I know we can do this:
```js
const config = Encore.getWebpackConfig();
if (config.devServer) {
// ....
}
```
but it means that we can't use webpack-encore methods:
```js
if (Encore.isDevServer()) {
Encore
.setPublicPath('http://app.vm:8080/build/')
.setManifestKeyPrefix('build/')
}
```
Also I tried to add some tests but I didn't find tests for `isProduction()` :(
Thanks!
=> Add new methods `isDev()` and `isDevServer()`

lib/config/validator.js, lib/webpack/shared-entry-concat-plugin.js
Just two small issues I noticed while playing with the TypeScript compiler :)
=> Fix small mistakes in shared-entry-concat-plugin.js and validator.js

test/utils/string-escaper.js
These logging calls are written in the output while running tests, which look weird in the test output.
I assume they were added to debug stuff while writing tests, but they should not be necessary anymore.
=> Remove debug logging in some tests

index.js, test/index.js
=> Add a public method to know whether the runtime is configured

index.js, lib/WebpackConfig.js, lib/config-generator.js, test/WebpackConfig.js, test/config-generator.js
This PR adds support for _properly_ configuring watching options.
References: #35, #126
Before, we had to do this:
```js
const config = Encore.getWebpackConfig();
if (config.devServer) {
config.devServer.watchOptions.poll = 250;
}
```
Now, we can do this:
```js
Encore.configureWatchOptions(watchOptions => {
watchOptions.poll = 250;
});
```
Also, I think it would be better to rename it to `configureWatchOptions()`, but I don't know how encore apply watching options to webpack when running dev or prod environment with `encore [prod|dev] --watch`. :thinking: 
Thanks!
---
**EDIT**: Ah, I found it! 
I will see how can I modify `watchOptions` in dev/prod modes.
=> feat: configure watching options

lib/plugins/terser.js
Recently Laravel Mix have sped up build time by configuring Terser plugin   (https://github.com/JeffreyWay/laravel-mix/pull/1925).
I though `cache` and `parallelism` options was already set on encore, but nope.
Here a comparaison, before:
and after:
From 16-18 seconds to 14-8 seconds on my machine. 
And even if my project does not have a tons of JavaScript, the building time have been reduced.
=> feat(terser): enable cache and parallelism

index.js, lib/WebpackConfig.js, lib/config-generator.js, test/WebpackConfig.js, test/config-generator.js
This is an alternative to https://github.com/symfony/webpack-encore/pull/472 which does not modify the public Encore API and requires the user to pass an array if they want to add multiple externals at a time.
=> Fix support for Webpack externals. This fixes #471

.travis.yml, fixtures/vuejs-typescript/tsconfig.json, test/bin/encore.js, test/functional.js, test/helpers/setup.js
This PR fixes various things that currently make the tests result indicators quite unreliable:
* Set a `DISABLE_UNSTABLE_CHECKS` environment variable and use it to disable some checks related to filenames with hashes that are subject to frequent changes (for instance `runtime.xxxxxxxx.js` when updating Webpack). This only applies to "Lowest versions of the dependencies" and "Highest versions of the dependencies" jobs.
* Fix the Vue.js + Typescript test that was silently failing in the "Lowest versions of the dependencies" job (no idea why it worked for the other ones...)
* Increase default timeouts of functional tests from 8s to 10s (since they were frequently failing because of that)
* Restore the standard output at the beginning of the compiler callback in `runWebpack()` (doing it later …
=> Fix various issues related to functional tests

fixtures/vuejs-css-modules/App.vue, fixtures/vuejs-css-modules/main.js, lib/config-generator.js, lib/loaders/css.js, test/functional.js, test/loaders/css.js
With the current version of Encore you are able to either:
* only use standard CSS (default behavior)
* only use CSS modules (by calling `Encore.configureCssLoader()`)
This PR should help detecting when `<style module>` is used and enabling css modules accordingly (fixes #460).
**Reference:** https://vue-loader.vuejs.org/guide/css-modules.html#opt-in-usage
=> Support CSS modules in Vue.js projects by default

fixtures/vuejs-css-modules/App.vue, lib/config-generator.js, lib/loaders/less.js, lib/loaders/sass.js, lib/loaders/stylus.js, test/functional.js, test/loaders/less.js, test/loaders/sass.js, test/loaders/stylus.js
As noted in https://github.com/symfony/webpack-encore/pull/508#issuecomment-460426555, that previous PR actually only added support for standard CSS modules, but didn't work for other languages.
This new PR makes it so it also works with the Scss, Less and Stylus syntaxes (using the same principle).
Ping @Chesskingt :)
=> Add CSS modules support in Vue.js for Sass/Less/Stylus

index.js, lib/WebpackConfig.js, lib/config-generator.js, test/WebpackConfig.js, test/functional.js
The current behavior of `copyFiles()` is to use the value of the `from` option as a context when copying files.
This means that when doing the following:
```js
Encore.copyFiles({
from: './assets/images',
to: '[path][name].[ext]',
includeSubdirectories: false,
});
```
Will end-up putting all the files from `./assets/images` directly at the root of the output directory.
Sometimes this is not the desired behavior (see https://github.com/symfony/webpack-encore/issues/490#issuecomment-453982520) which is why this PRs adds a `context` option to `copyFiles()` entries (closes #490).
For instance:
```js
Encore.copyFiles({
from: './assets/images',
to: '[path][name].[ext]',
includeSubdirectories: false,
context: './',
});
```
Will put all the copied files inside of an `./assets/images` folder in the …
=> Allow to set a custom context in copyFiles

index.js, lib/package-helper.js, test/bin/encore.js
This PR:
- Removes the stacktrace from the "_Install x to use y_" error message by throwing a string instead of an `Error` (fixes #420)
- Only keeps the second line of the stacktrace for the "_Unrecognized method_" error message (since this is most likely the one related to the `webpack.config.js` file)
- Fixes the "_Did you mean xxxx_" advice that was broken since the `Encore` object became a `class`
---
**Install x to use y**
Before: 
After:
---
**Unrecognized method**
Before:
After:
=> Improve 'Install x to use y' and 'Unrecognized method' error messages.

index.js, lib/WebpackConfig.js, lib/loaders/babel.js, test/WebpackConfig.js, test/config-generator.js
This PR adds an `useBuiltIns` option to the second parameter of `Encore.configureBabel()` that sets the same option on the`@babel/preset-env` preset.
That option allows to change how the preset handles polyfills (fixes #444), for instance:
```js
Encore.configureBabel(() => {}, {
// automatically import individual polyfills
// where they are needed
useBuiltIns: 'usage';
});
```
The PR also depreciates the `include_node_modules` option and replaces it by `includeNodeModules` since other methods (for instance `Encore.enableSassLoader()`) use camelCased names.
=> Allow to set @babel/preset-env's useBuiltIns option

lib/webpack/shared-entry-concat-plugin.js
This PR fixes #493.
When using `dev-server --hot` an additional `.hot-update.js` file can be [added to the list of files associated to a chunk](https://github.com/webpack/webpack/blob/7076c05353bae6d788247cfcaa94704f34cca292/lib/HotModuleReplacementPlugin.js#L287). If that list contains another JS file the current version of Encore throws an Error that causes the compilation to fail.
The good news is that the `.hot-update.js` file is also [added to the `additionalChunkAssets`](https://github.com/webpack/webpack/blob/7076c05353bae6d788247cfcaa94704f34cca292/lib/HotModuleReplacementPlugin.js#L284) property of the `compilation` object. This allows us to ignore it and only keep the JS file that we need.
=> Ignore hot-update files in the SharedEntryConcatPlugin

lib/WebpackConfig.js, test/WebpackConfig.js
This PR changes the check that is currently made when calling `setOutputPath` in order to allow the creation of nested directories (closes #189).
Note that it doesn't remove it entirely since it still prevents the creation of more than one level when the output path is located outside of the context path.
For instance, given the context is `/home/foo/bar/`:
```js
// Will work
Encore.setOutputPath('build');
// Will work, even if "/home/foo/bar/public" does not exist
Encore.setOutputPath('public/build/output');
// Will work, even if "/home/foo/public" does not exist
Encore.setOutputPath('../public');
// Will work if only "/home/foo/public/build" does not exist
// ... but **won't** work if "/home/foo/public" does not exist
Encore.setOutputPath('../public/build');
```
=> Allow setOutputPath to create nested directories

lib/config/parse-runtime.js
I'm using docker (one container for the front, another one for webpack)
and I had to do this PR to make it work.
For reference, this is the command I (docker actually) executed
```
yarn run dev-server --host 0.0.0.0 --port 9999 --hot --public https://example.com:443 --disable-host-check
```
=> Honor --public flag given to 'yarn run dev-server ...'

index.js, lib/WebpackConfig.js, lib/config-generator.js, test/WebpackConfig.js
While reviewing https://github.com/FriendsOfSymfony/FOSCKEditorBundle/pull/174 I was a bit surprised that calling `copyFiles` with a string as a `pattern` (instead of a `RegExp`) worked fine.
It turns out that's not an issue since the `copyFiles` method causes the creation of a temporary `.js` file in which the `RegExp` is casted to a string anyway.
However, what *is* an issue is that using a string that does not contain a valid regular expression can break that temporary file.
For instance:
```js
Encore.copyFiles({
from: './assets',
pattern: 'foo;'
});
```
Will generate something like:
```js
const context_0 = require.context(
'!/* ... */',
true,
foo; // <= Syntax error here
);
context_0.keys().forEach(context_0);
```
This PR doesn't prevent using strings for that option because I don't …
=> Add some checks to the 'pattern' option of Encore.copyFiles()

lib/loaders/babel.js, test/loaders/babel.js
Currently `cacheDirectory` is always set to `true` in `babel-loader`'s options.
This can be an issue because the cache identifier is only based on direct Babel options, but not on external configs such as `.browserslistrc` files or if a `browserslist` key was added to the `package.json` (see https://github.com/babel/babel-loader/issues/690).
Disabling that cache entirely in Encore while waiting for a proper solution in `babel` or `babel-loader` would probably not be a good idea, but we could mitigate the problem by disabling it only for the prod environment.
Closes #514
=> Don't use babel-loader's cacheDirectory for production

index.js, lib/WebpackConfig.js, lib/config-generator.js, test/WebpackConfig.js, test/config-generator.js, test/loaders/eslint.js
This PR is a proposal to resolve #473 and #504 in a clean way.
`Encore.configureLoaderRule()` is a low-level function, and has for goal to let the user having full access to Webpack loaders rules (what we push into `module.rules`) and configure them.
This is the implementation of the idea I had in https://github.com/symfony/webpack-encore/pull/504#discussion_r252145493.
For resolving Vue files linting issue, the next example would be the ideal solution  I think:
```js
Encore
.configureLoaderRule('eslint', loader => {
loader.test = /\.(jsx?|vue)$/
});
// actually, the equivalent code is something like this:
const webpackConfig = Encore.getWebpackConfig();
const eslintLoader = webpackConfig.module.rules.find(rule => rule.loader === 'eslint-loader');
eslintLoader.test = /\.(jsx?|vue)$/; …
```
=> feat: Add method to configure loaders rules 

fixtures/copy/foo.css, fixtures/copy/foo.js, fixtures/copy/foo.json, lib/config-generator.js, lib/webpack/copy-files-loader.js, test/functional.js
This PR fixes #535.
As explained in the issue, the current version doesn't allow `Encore.copyFiles()` to process JSON files because of how Webpack 4 handles them.
Basically, from what I understand, for most of the files it works that way:
```
Imported file (module.type = javascript/auto)
=> file-loader (takes anything, returns JS content)
=> Webpack JS parser
```
But for `.json` files the JS parser is replaced by a JSON parser:
```
Imported file (module.type = json)
=> file-loader (takes anything, returns JS content)
=> Webpack JSON parser
```
Since that "Webpack JSON parser" part expects JSON data (and not something that contains JS), the compilation fails at that point.
There is no way to disable that behavior when you specify loaders the "inline" way... which is what we do for …
=> Fix JSON files support in Encore.copyFiles()

fixtures/js/css_import.js, index.js, lib/WebpackConfig.js, lib/config-generator.js, lib/loaders/css-extract.js, test/WebpackConfig.js, test/functional.js, test/index.js
This PR adds an `Encore.disableCssExtraction()` method that allows to disable the `mini-css-extract-plugin` and use the `style-loader` instead.
It can be used to solve various problems that, until now, required a really ugly workaround that relied on our internal implementation (for instance the following commit probably broke some builds that used previous versions of it: https://github.com/symfony/webpack-encore/commit/68674433f9feb94e34c473c4b9cf5d7c40df515d#diff-8beacd21a12ca072bafa4e8e3f1aae6b).
Related issues: #3, #256, #348, #527
=> Add Encore.disableCssExtraction() to the public API

index.js, lib/utils/pretty-error.js
This PR fixes #533 by slightly modifying the default theme of `pretty-error` so it doesn't use a color for the error message.
**Before:**
**After:**
=> Fix the color of error messages when they are displayed on a light theme

index.js, lib/WebpackConfig.js, lib/loaders/babel.js, package.json, test/config-generator.js, yarn.lock
While working on #544 I noticed that the latest version of `@babel/preset-env` displayed a warning (which luckily made [one of the tests](https://travis-ci.org/symfony/webpack-encore/jobs/509655320) fail):
```
WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version.
Currently, we assume version 2.x when no version is passed.
Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.
You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section.
If it doesn't, you need to run one of the following commands:
npm install --save core-js@2    npm install --save …
```
=> Set useBuiltIns to false by default and allow to set core-js version

index.js, lib/WebpackConfig.js, lib/plugins/entry-files-manifest.js, test/WebpackConfig.js, test/functional.js, test/index.js
This PR adds an `Encore.enableIntegrityHashes()` method that allows to compute integrity hashes of all the files referenced in the `entrypoints.json` (closes #418).
For instance:
```js
// Enable it for all builds with the
// default hash algorithm (sha384)
Encore.enableIntegrityHashes();
// Enable it only in production with
// a custom hash algorithm
Encore.enableIntegrityHashes(
Encore.isProduction(),
'sha512'
);
```
And here is the resulting `entrypoints.json` file:
```json
{
"entrypoints": {
"main": {
"css": [
"/main.3d1dcb7e.css"
],
"js": [
"/main.7c6b7c81.js"
]
}
},
"integrity": {
"/main.3d1dcb7e.css": "sha384-ce7d1nV3CFoSIfinwm53befb9CMHNAAlPEb61deOf3zBvpXK9lct44/U2ieSOKt4",
"/main.7c6b7c81.js": "sha384-kHFhNTJlbSuDijSTimOHZGTxKzlLYCWc03AmmRSAE3b173SMlGiQG6uasAzl29+0"
}
}
```
=> Add an enableIntegrityHashes() method to the public API

lib/features.js
Just a minor typo, renaming `VUE` to `Vue`.
=> Fix typo in Vue features

index.js
Putting #550 and #551 together :)
=> Putting jsdoc in markdown

README.md
Following of #571, it can be nice to have a badge that shows the lowest supported version of Node.
Under the hood, it uses `engines.node` from [`package.json`](https://github.com/symfony/webpack-encore/blob/master/package.json#L24)
=> doc: add badge for lowest supported Node version

lib/EncoreProxy.js, lib/WebpackConfig.js, lib/config/path-util.js, lib/friendly-errors/transformers/missing-css-file.js, lib/friendly-errors/transformers/missing-loader.js, lib/friendly-errors/transformers/missing-postcss-config.js, lib/package-helper.js
Some small internal changes.
It replaces some calls to `.indexOf()` with `.includes()` which is more readable:
- `a.indexOf(b) === -1` -> `!a.includes(b)`
- `a.indexOf(b) !== -1` -> `a.includes(b)`
=> minor #583 chore: replace some `.indexOf() === -1` with `.includes()` (Kocal)

package.json, yarn.lock
A version `^2.0.0-beta.1` of `friendly-webpack-plugin` was released recently, the API doesn't seem to change at all and it fixes a bunch of things, including #445.
The major version bump is only there because they dropped support for Webpack 3, which shouldn't impact us at all.
=> Update friendly-errors-webpack-plugin to ^2.0.0-beta.1

lib/friendly-errors/transformers/missing-loader.js
In `webpack@4.34.0` having a missing loader can trigger a "You may need an **additional** loader" error message instead of the one we are currently looking for ("You may need an **appropriate** loader"), which causes one of our CI jobs to fail.
This PR fixes it by detecting both versions.
Related commit: https://github.com/webpack/webpack/commit/45582c51e7faf2d7c1ee0f39a4f763accb367b8a#diff-34f95d7b09e1170360b8660f36c8b96fR26
=> Fix "Missing loader" detection in Webpack 4.34.0+

fixtures/copy/foo.png, lib/config-generator.js, lib/webpack/copy-files-loader.js, test/functional.js
This PR adds some extra checks to make sure that files *really* match the pattern used in `copyFiles(...)` before the `file-loader` is called (closes #556).
For a full description of the issue see https://github.com/symfony/webpack-encore/issues/556#issuecomment-481440004, but here is a TL;DR:
Currently, if you have a folder that contains a `foo.js` file and calls `copyFile(...)` with a pattern that excludes `.js` files, that file will still be copied.
This is caused by the `resolve.extensions` mechanism of Webpack that also applies to `require.context(...)` calls (on which this feature relies) and includes `./foo` (without the extensions) to the list of files that should be imported.
=> Add extra checks to the copyFiles feature

fixtures/css/postcss_extension.postcss, fixtures/vuejs-css-modules/App.vue, lib/config-generator.js, test/config-generator.js, test/functional.js
This PR closes #592 by making the `.css` rule also process `.postcss` files when `Encore.enablePostCssLoader()` has been called.
It seems that it can be useful in a Vue.js context in order to have proper syntax highlighting in IDEs by using `lang="postcss"`, as explained on https://vue-loader-v14.vuejs.org/en/features/postcss.html:
> Since vue-loader handles PostCSS on its styles internally, you only need to apply postcss-loader to standalone CSS files. There's no need to specify lang="postcss" on a style block if there is a PostCSS config file in your project.
>
> Sometimes the user may want to use lang="postcss" only for syntax highlighting purposes.
=> Add support for .postcss files

index.js, lib/WebpackConfig.js, lib/loaders/sass.js, package.json, test/loaders/sass.js
This PR solve the error below, occuring on some cases:
```
Error: resolve-url-loader: CSS error
source-map information is not available at url() declaration (found orphan CR, try removeCR option)
```
See discussion: bholloway/resolve-url-loader#107
=> Allow to configure the resolve-url-loader

lib/WebpackConfig.js, lib/plugins/plugin-priorities.js, lib/plugins/versioning.js, package.json, test/WebpackConfig.js, test/functional.js, yarn.lock
This PR removes the `webpack-chunk-hash` plugin since:
* using `[chunkhash]` was deprecated a while ago (in #463)
* it seems to be causing issues even when `[chunkhash]` is not used at all (fixes #605)
=> Remove webpack-chunk-hash plugin

lib/plugins/entry-files-manifest.js
This PR fixes a really small issue that I noticed while working on #608.
When using `--watch` and `enableIntegrityHashes()` together it works fine for the first compilation, but on the next ones the old hashes also get added to the `entrypoints.json` file.
**First compilation:**
```json
{
"entrypoints": {
"main": {
"js": [
"/build/main.js"
]
}
},
"integrity": {
"/build/main.js": "<OLDHASH>"
}
}
```
**Second compilation:**
```json
{
"entrypoints": {
"integrity": {
"/build/main.js": ["<OLDHASH>"]
},
"main": {
"js": [
"/build/main.js"
]
}
},
"integrity": {
"/build/main.js": "<NEWHASH>"
}
}
```
=> Fix old integrity hashes being added to the entrypoints.json with --watch

fixtures/js/async_function.js, lib/loaders/babel.js, test/functional.js
This PR removes the `forceAllTransforms: webpackConfig.isProduction()` line that is currently added to `@babel/preset-env`'s options.
That setting was previously needed because UglifyJS did not support ES6 which meant that if you, for instance, had `async` functions in your code and targeted a recent browsers, they would have to be transformed for the minification process to be successful.
Nowadays we're using Terser which supports ES6, so there shouldn't be any issue keeping these kind of things in the final code anymore.
=> Don't make @babel/preset-env force all transforms in prod

lib/utils/get-file-extension.js, lib/webpack/shared-entry-concat-plugin.js, test/functional.js, test/utils/get-file-extension.js
This PR fixes #618 by correctly filtering the JS files of the shared entry (in the `SharedEntryConcatPlugin`) when versioning is handled in a query string.
=> Fix createSharedEntry(...) when using query string versioning strategy

test/functional.js
The runtime changes are probably due to the yarn.lock bump, which now includes
https://github.com/webpack/webpack/pull/9493
The one main.js change is a mystery.
=> Fixing hashes in tests

lib/config-generator.js, test/config-generator.js
Currently pre-defined aliases (used by `vue` and `preact-compat`) are added after the ones from `Encore.addAliases(...)`, which prevents overwriting them using this method.
It makes more sense to change that order so aliases from `Encore.addAliases(...)` are always added last (fixes #625).
=> Allow to overwrite pre-defined aliases using addAliases()

lib/WebpackConfig.js, lib/loaders/babel.js, test/loaders/babel.js
This PR allows you to configure `@babel/preset-env` by calling `Encore.configureBabelPresetEnv()` without the need to create a `.babelrc` and lose the ability to activate presets automatically.
```js
Encore
.configureBabelPresetEnv((config) => {
config.corejs = 3;
config.useBuiltIns = 'usage';
config.include = ['foo-plugin'];
});
```
The options `corejs` and `useBuiltIns` of `Encore.configureBabel()` should be deprecated.
=> Allow to configure babel env preset

test/functional.js
Fix a broken test on develop following the merge of #648.
Not sure why the main.js and runtime.js hashes changed, but their content stayed exactly the same.
=> Fix hashes in the "Copy with versioning enabled" test

index.js, test/config-generator.js, test/index.js
This PR adds the missing method `configureBabelPresetEnv()` to the `index.js` file (fixes #666).
=> Add Encore.configureBabelPresetEnv() to the public API

lib/WebpackConfig.js, test/WebpackConfig.js
Since we do not configure `@babel/preset-env` if there is a `.babelrc` file (or something similar) it makes sense to add the same warning we already have for the `Encore.configureBabel()` function to `Encore.configureBabelPresetEnv()`:
> The "callback" argument of \<function\> will not be used because your app already provides an external Babel configuration (a ".babelrc" file, ".babelrc.js" file or "babel" key in "package.json
This PR also removes some deprecation that were added by #642.
We talked about them with @weaverryan and it's probably not worth removing the `useBuiltIns` and `corejs` options of `Encore.configureBabel()`:
* they are currently recommended by the flex recipe
* it allows us to document them/check them easier than with a callback
=> Add .babelrc error to configureBabelPresetEnv and remove some deprecations

lib/config-generator.js, test/config-generator.js, test/functional.js, test/helpers/assert.js
When `config.devtool` is not set (which is the current behavior with `enableSourceMaps(false)` or when the function is not called at all) the `eval` source maps type is used in development mode.
This PR sets the default value to `false` to make sure that no source map is being generated in those cases (fixes #695).
=> Fix source maps being generated by default in dev

lib/webpack/copy-files-loader.js, test/functional.js
This PR should fix #647 by passing the `regExp` option to the `file-loader` used by `Encore.copyFiles()`.
It's a bit hacky since it changes the loader's options from the loader itself, but we should probably be fine for a while (I also tested it with `webpack@5.0.0-alpha.29` and the latest version of `file-loader@4.2.0`).
=> Allow to use the [N] placeholder in copyFiles()

fixtures/js/eslint-es2018.js, index.js, lib/WebpackConfig.js, lib/features.js, lib/loaders/eslint.js, lib/package-helper.js, test/config-generator.js, test/functional.js, test/helpers/setup.js, test/loaders/eslint.js
Hi :hand:
This PR is a proposal for #657 implementation and should fix issues encountered in #473, #574, #656, #659, and #685.
As discussed in #657, it would be better if Encore didn't configure ESLint itself. It should be done by the end user in an configuration file (e.g.: `.eslintrc.js`)
ESLint's `parser` option is not configured by default anymore, and `babel-eslint` requirement has been removed. We can considering this as a breaking change, end users should now configure `parser: 'babel-eslint` themselves.
Method `Encore.enableEslintLoader('extends-name')` has been deprecated and undocumented, in order to prevent end users to configure ESLint through Encore.
A nice message is also displayed when no ESLint configuration is found:
I couldn't use `FriendlyErrorsPlugin` for this because …
=> Remove ESLint user-related config

lib/loaders/css-extract.js, package.json, yarn.lock
The webpack encore version style loader is too old and inject CSS using `<link>` instead of `<style>`. This solution loads style asynchronously cause lots of problem with JavaScript.
With this upgrade style-loader doesn't accept sourcemap anymore. SourceMap support is calculated from previous loaders (https://github.com/webpack-contrib/style-loader#source-maps)
=> bump: style-loader version 1.X

package.json, yarn.lock
I think it suddenly failed because a `@types/*` package required by another dependency got updated and was not compatible with our lowest allowed version of Typescript anymore.
=> Fix failing 'Lowest versions' tests

lib/config-generator.js, test/config-generator.js
This PR adds support for the `.pcss` file extension for PostCSS files.
I've got this to work by overriding the CSS Loader `test` within my webpack.config.js using the `.configureLoaderRule()` as documented in https://www.oliverdavies.uk/articles/using-the-pcss-extension-with-webpack-encore.
But it would be nice to have this supported by default to make things simpler and not having to see the `Be careful when using Encore.configureLoaderRule()` message on each build.
=> Include the .pcss extension for PostCSS files

index.js, lib/WebpackConfig.js, lib/config-generator.js, lib/loaders/eslint.js, test/WebpackConfig.js, test/config-generator.js, test/loaders/eslint.js
This PR add a second argument to `Encore.enableEslintLoader()` that is used to let the ESLint loader lint `.vue` files:
```js
Encore.enableEslintLoader(() => {}, {
lintVue: true
});
```
Using `lintVue` won't add any ESLint configuration, that the job of the final user (see https://github.com/symfony/webpack-encore/pull/504#issuecomment-489221040).
**EDIT:**
While #657 is being discussed, you can use the following code to:
- let ESLint process your `.vue` files
- prevent the error `Use the latest vue-eslint-parser.`, see #656 
```js
Encore.enableEslintLoader((options) => {
delete options.parser;
}, {
lintVue: true
});
```
**EDIT 2:**
PR #687 has been merged and issue #657 is now resolved. It means that you can use the following code to let eslint-loader handle `.vue` files: 
```js …
```
=> Proposal to replace #504 (ESLint/Vue)

lib/loaders/css.js, package.json, test/functional.js, test/loaders/css.js, yarn.lock
Fixes #728 
Breaking changes here: https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md#300-2019-06-11
It doesn't look like anything that affects us directly, though users with customizations could, of course, be affected (or people who are using the `@value` thing).
=> bumping to css-loader v3

.appveyor.yml, .travis.yml, package.json, test/functional.js, yarn.lock
* Upgrades file-loader from v1 to v6
* Upgrades url-loader from allowing v1 or v2 to v4
* Removes support for Node 8
=> Upgrade file-loader and allowed version for url-loader, drop Node 8 support

lib/loaders/eslint.js, package.json, yarn.lock
Someone on Slack had an issue with Encore and ESLint 6:
`CLIEngine#config` does not exists on ESLint 6 anymore, since [6ae21a4b](https://github.com/eslint/eslint/commit/6ae21a4bfe5a1566f787fbad798182a524b96d28#diff-3daec82d5218d64d8f2fed4d21f8e6ccL472-L486). 
Now we can use [`CLIEngine#getConfigForFile`](https://eslint.org/docs/developer-guide/nodejs-api#cliengine-getconfigforfile) to get the ESLint configuration.
Encore now supports both ESLint 5 and 6.
cc @a-menshchikov :smile:
=> feat: add ESLint 6 support

package.json, yarn.lock
eslint-loader ^3 is the last version to [support both ESLint 5 and 6](https://github.com/webpack-contrib/eslint-loader/blob/v3.0.4/package.json#L40) (related #732).
Given the [changelog for v3.0.0](https://github.com/webpack-contrib/eslint-loader/blob/master/CHANGELOG.md#300-2019-08-24), the only breaking changes are:
- drop support for Node < 8.9.0 (we did it too https://github.com/symfony/webpack-encore/pull/731)
- minimum supported webpack version is 4: not a problem
- minimum supported eslint version is 5: not a problem
=> build(deps-dev): update eslint-loader to ^3

lib/WebpackConfig.js, lib/config/parse-runtime.js, test/config/parse-runtime.js
Since v7 [Babel supports two types of config formats](https://babeljs.io/docs/en/config-files):
- Project-wide configuration
- `babel.config` files, with the different extensions (`json`, `js`, `cjs`, `mjs`)
- File-relative configuration
- `.babelrc` files, with the different extensions (none, `json`, `js`, `cjs`, `mjs`)
- `package.json` files with a "babel" key
Encore, however, only checks for the existence of **file-relative** config files.
This is a problem if you want to compile packages from the `node_modules` folder (via `.configureBabel(null, {includeNodeModules: ['...']})`) because **project-wide** configuration files are needed for this.
This means that if you only have a `.babelrc.js` file, the package from the `node_modules` folder **will** be compiled by Babel, but **without** …
=> Fix babel config file detection

lib/config-generator.js, lib/loaders/babel.js, lib/loaders/css-extract.js, lib/loaders/css.js, lib/loaders/handlebars.js, lib/loaders/less.js, lib/loaders/sass.js, lib/loaders/stylus.js, lib/loaders/typescript.js, lib/loaders/vue.js, test/config-generator.js, test/loaders/sass.js
This issue fixes #727 by replacing the use of loader names in rules (for instance `'file-loader'`) by their resolved path (`require.resolve('file-loader')`).
The problem with using their name is that we are assuming that the loader's package will be present at the top-level of `node_modules`.
If for some reason that's not the case and npm/Yarn decides to put it in, let's say `node_modules/@symfony/webpack-encore/node_modules`, the compilation will fail when Webpack tries to require it.
Another reason to do that is to ensure that Webpack uses the right version of a loader. We had some issues before 0.29 because we expected an old version of `file-loader` when some other packages included a newer one that was then used by Webpack because it got hoisted to the top-level `node_modules`.
This …
=> Resolve loaders directly from Encore instead of using their names

.appveyor.yml, package.json, test/functional.js, yarn.lock
This doesn't affect end-users. I'm doing this mostly to isolate what test "hash" changes are unique to Vue 3 in #746 and which are just from upgrading dependencies.
=> [Chore] Updating lock dependencies

CHANGELOG.md
As noted in https://github.com/symfony/webpack-encore/issues/743 the file-loader update we did in 0.29.0 has a breaking change when files are imported using the CommonJS syntax.
Since the loader is now exporting ES modules by default, importing them with `require(...)` retrieves the whole module and not only the default export.
We'll also have to update the Github changelog after merging this (closes #743).
=> Update 0.29.0 changelog regarding CommonJS imports following the file-loader update

CHANGELOG.md, package.json, yarn.lock
Closes #749 
It seems like there weren't many changes for `fork-ts-checker-webpack-plugin`, unless you were hooking into it in custom ways or using certain options. It will be the user's responsibility to upgrade anyways: if they're using an older version, they'll just see a warning from us.
=> upgrading fork-ts-checker-webpack-plugin to test 4.0

CHANGELOG.md, lib/config-generator.js
=> Removing vue2 alias to use the full build

CHANGELOG.md, index.js, lib/WebpackConfig.js, lib/config-generator.js, lib/friendly-errors/transformers/missing-loader.js, lib/utils/manifest-key-prefix-helper.js, test/WebpackConfig.js, test/config-generator.js
Using the runtime build by default makes it harder for beginners and it's hard to know the fix. Specifically, if you follow the "intro docs" to Vue, you will likely try this:
```js
var app = new Vue({
el: '#app',
data: {
message: 'Hello Vue!'
}
})
```
which will not work (and the error will be tough for beginners to spot). As a compromise, on a production build, we print a recommendation so that people can discover the option to use the smaller build.
=> Reverting change to only package vue runtime loader

lib/plugins/clean.js
There is currently a bug where, on a "watch" rebuild, sometimes an image that's referenced from a CSS file won't be "noticed" and will be mistakenly deleted.
Reproducer: https://github.com/weaverryan/clean_webpack_assets_watch_bug
I haven't had time yet to "distill" that reproducer down to a raw `webpack.config.js` file (without Encore) so that I can submit an issue. But, since this behavior can be quite damaging (I was pulling out my hair trying to figure out why an image file was there sometimes and gone other times) and because the `cleanStaleWebpackAssets` is so *minor* (it removes extra files on `watch` rebuilds), I think we should just disable it by default.
=> Setting CleanWebpackPlugin's cleanStaleWebpackAssets: false

package.json, yarn.lock
This upgrades `assets-webpack-plugin` to 5.0.3.
This is a new major version of the plugin, however according to https://github.com/ztoben/assets-webpack-plugin/blob/HEAD/changelog.md that is only due to the plugin now requiring node 10.
Since encore already requires node 10 this is not a problem.
The older version of `assets-webpack-plugin` depends on an unsafe version of `lodash` that causes `npm audit` to fail (https://npmjs.com/advisories/1523)
Fixes #806
=> Upgrade assets-webpack-plugin to ^5.0.3

index.js
Babel supports 2 different types of config files:
- `.babelrc` stops at package boundaries
- `babel.config.*` applies to the whole project, including `node_modules`
Once node_modules is not excluded anymore in the babel-loader configuration, this distinction matters.
Refs #785
=> Update the JSDoc of configureBabel to warn about .babelrc and node_modules

.travis.yml, package.json
This PR is a proposal for the Node.js 11 support issue I encountered in #774.
=> feat(node): drop support for node 11 (end-of-life since 1 year)

index.js
The implementation actually defines 3 provided variables, not only 2.
=> Fix the documentation about autoProvidejQuery

yarn.lock
The PR #859 has modified the `package.json` but forgot to update the `yarn.lock`, making all CI builds failing (because we use `yarn --frozen-lockfile`).
cc @fabpot @weaverryan :pray:
=> chore: sync yarn.lock after #859 updates

lib/features.js, lib/plugins/stimulus-bridge.js
Fix #861 
Testing my modification on a new Symfony repository but removing `@symfony/stimulus-bridge` and `stimulus` dependencies.
If you try to use `.useStimulusBridge()` without those depdendencies installed, you now have this friendly error message:
When you install the dependencies, everything is okay:
When you don't use `.useStimulusBridge()` and don't have installed Stimulus dependencies, you have no errors anymore about those missing deps, since they are not required. 
Here, the errors are coming from the app code (from the Symfony recipe) I didn't have update, but it's fine:
cc @fabpot @weaverryan
=> fix(stimulus): don't require an optional dependency if it's not used

lib/config/validator.js, test/config/validator.js
=> Validator should allow copyFiles() without other entries.

package.json, yarn.lock
Resolves #703 
~~Tests: ✔️ [Node 10](https://github.com/skmedix/webpack-encore/runs/843779672?check_suite_focus=true) | ✔️ [Node 12](https://github.com/skmedix/webpack-encore/runs/843779686?check_suite_focus=true)~~
=> ⬆️ Upgraded ts-loader to ^8.0.1

.eslintrc.js, lib/loaders/eslint.js, package.json, test/.eslintrc.js, yarn.lock
- bump eslint from `^5.15.2 || ^6.0.0` to `^6.0.0 || ^7.0.0`: https://eslint.org/blog/2020/05/eslint-v7.0.0-released
- bump eslint-loader from `^3.0.0` to `^4.0.0`, which drop support for Node <10.13.0 and set minimum ESLint support to version 6: https://github.com/webpack-contrib/eslint-loader/blob/master/CHANGELOG.md#400-2020-04-03
- had to fix some linting issues
**EDIT:** Ok so ESLint 7 is not compatible with Node 11. 
This version is in end of life ([End-of-Life releasese](https://github.com/nodejs/Release#end-of-life-releases), should we drop support for Node 11 too? And maybe add support for Node 13 and Node 14?
WDYT? 
**EDIT 2:** PR opened at #775 
**EDIT 3:** PR rebased since #775 has been merged
=> feat: add support for ESLint 7, drop support ESLint 5

index.js, lib/WebpackConfig.js, test/WebpackConfig.js
Branch? | master
-- | --
Bug fix? | no
New feature? | yes
Deprecations? | no
Tickets | none
License | MIT
Allows for environment specific uses of disableCssExtraction that match conventions used in webpack.config.js by other methods such as enableSourceMaps or enableVersioning
=> Add a boolean parameter to Encore.disableCssExtraction()

test/functional.js
One of the new tests is currently missing a call to `done()` which breaks the output of the next tests:
=> Add missing call to done() in the Stimulus functional test

lib/features.js, package.json, yarn.lock
This will change the recommendation to `sass` instead of `node-sass` which is deprecated and harder to deal with. I haven't had any issues or differences working with `sass` yet vs `node-sass`.
I also upgraded the lock file in general, it makes it easier to see what packages are legitimately out of date and doesn't affect end users.
=> Prefer sass over node-sass

fixtures/stimulus/controllers/index.js
Following the proposal of https://github.com/symfony/stimulus-bridge/pull/1, this PR checks ES module syntax work as expected.
=> Update Stimulus test to use an ES syntax

.travis.yml, lib/config-generator.js, package.json, test/config-generator.js, test/functional.js, yarn.lock
2 quick, minor follow-ups from #645.
* Removed Node 13, as it is no longer supported
* Changed the ignored back to a regular expression, which it was originally and once again a regexp works: https://github.com/symfony/webpack-encore/pull/645#discussion_r546402665
* Upgraded to Stimulus 2, which the stimulus bridge now depends on
=> [Webpack5] Using old watchOptions regexp & removing Node 13 support

CHANGELOG.md, index.js, lib/WebpackConfig.js, lib/config-generator.js, test/WebpackConfig.js, test/config-generator.js, test/functional.js, test/index.js
Hi!
This is a very simple feature, but it can also easily be improperly used. It is part of #880. See some comments about it from @Lyrkan from #645:
> Things can easily go wrong with persistent caching... even only enabling it for the config file could lead to some issues if not done properly (for instance if the config use values coming from environment variables, which is far from an edge case imo: https://github.com/webpack/changelog-v5/blob/master/guides/persistent-caching.md#version).
The trick, for us, is to:
A) Make sure we are doing everything as correctly as we can. For example, I assume that WE don't need to include `.babelrc` or `postcss.config.js`, but I actually don't know that for sure. Should we also potentially be adding Encore itself to the build dependencies?
B) Good …
=> [Webpack 5] Adding new enableBuildCache() method for Webpack 5 persistent caching

package.json, yarn.lock
This helps fix https://github.com/symfony/stimulus-bridge/pull/16
Basically, in the Encore recipe, we add the `@babel/plugin-proposal-class-properties` plugin in `webpack.config.js`. But, this is not necessarily in the user's project. But 7.10 of `@babel/preset-env` started including this package.
So it's a bit of an odd solution, as we're bumping this dependency so that users can do something simpler in userland config, but I think it's the simplest path. This is basically why most users already are able to use Stimulus (and the class properties it uses) without issues, as most people probably already have `@babel/preset-env` 7.10 or higher.
=> bumping preset-env to version that depends on @babel/plugin-proposal-class-properties

lib/logger.js
This was originally done so that they all lined up nicely in a column. But I noticed that Webpack (at least v5) consistently uses just one space around each.
=> normalizing width of logger categories

CHANGELOG.md
This should be updated in the release notes, too.
=> Fix replaced package name in changelog

CHANGELOG.md, bin/encore.js, lib/WebpackConfig.js, lib/config-generator.js, lib/config/RuntimeConfig.js, lib/config/parse-runtime.js, test/config-generator.js, test/config/parse-runtime.js
=> Fixing support for webpack-dev-server v4

lib/plugins/stimulus-bridge.js, test/functional.js
Discussing with @tgalopin, to make life simpler (and more semver, even though stimulus-bridge is experimental), the stimulus-bridge that contains the plugin/loader changes will be 2.0.
=> next stimulus-bridge will actually be 2.0

index.js, lib/plugins/clean.js, test/plugins/clean.js
This fixes the 2nd part of #893 - https://github.com/symfony/webpack-encore/issues/893#issuecomment-769488763
On Webpack 5, there is some miscommunication between the CleanWebpackPlugin and the WebpackManifestPlugin when using `dev-server`.
The `WebpackManifestPlugin` *does* emit the physical `manifest.json` file, but CleanWebpackPlugin then deletes it. CleanWebpackPlugin should just remove files *before* we start, and not delete anything that's emitted. I'm not sure which plugin has the bug. But, the work around is quite clean.
=> Working around missing manifest.json bug

lib/config-generator.js
Fixes an issue where `yarn watch` or `yarn dev-server` had super slow "rebuilds" - as long as the initial build, which is much different than the pre-1.0 version of Encore. 
It appears that cache: false is different than omitting the cache key entirely. Using cache: false appears to even disable in-memory caching that Webpack does when rebuilding in "watch" mode or for the dev-server
=> Omit cache key entirely when build cache is disabled

fixtures/stimulus/assets/controllers.json, lib/plugins/stimulus-bridge.js, package.json, yarn.lock
stimulus-bridge 2.0 has been released!
This fixes a bug where I forgot to allow v2. It also stops relying on the version (which wouldn't work when v3 comes out) to determine if the plugin (from v1) should be used or not. It also issues a deprecation warning to help users upgrade.
=> Fix stimulus version bug

package.json
This was bumped in https://github.com/symfony/webpack-encore/pull/645
Ubuntu LTS [ships node 10.19](https://packages.ubuntu.com/focal/nodejs) by default.
If we can, let's save ppl (aka me) from installing yet another ppa.
=> Allow node 10.19

lib/WebpackConfig.js, lib/config-generator.js, lib/config/RuntimeConfig.js, lib/config/parse-runtime.js, lib/config/path-util.js, lib/config/validator.js, test/WebpackConfig.js, test/config-generator.js, test/config/parse-runtime.js, test/config/path-util.js
Hi!
Fixes #903
If you pass `--https` at the command line, that overrides your `devServer.https` config. In webpack-dev-server v3, that wasn't a problem. But in v4, the certificate config was moved under `devServer.https`, which can now be an object. This meant that if you passed `--https` at the command line (which Encore previously required) but also set `devServer.https = { ... }`, that would be "re-set" back to `devServer.https = true` and your config would be lost.
The fix is to not require the `--https` flag and look at it or the user's config to determine if the dev-server is running in https.
Cheers!
=> Re-working dev-server and https detection

lib/config-generator.js, lib/plugins/manifest.js, test/config-generator.js, test/functional.js
This PR fixes an issue that prevented `Encore.copyFiles()` from working properly when copying files that matched one of the default `asset/resource` rules.
Note that it has two drawbacks:
* it introduces what could be considered as a small breaking change for users calling `configureLoaderRule('images', ...)` or `configureLoaderRule('fonts', ...)` since it adds a new `oneOf` at the top-level of each rule
* if an user create a new rule that also matches files handled by `Encore.copyFiles(...)` they'll have to use the same `oneOf`/`resourceQuery` pattern to avoid conflicts
Closes #894
=> Fix Encore.copyFiles() when copying images/fonts

lib/features.js
Due to the `generator` we use with asset modules, we need 15.9.5 (if you're using Vue 2, or any vue-loader 16 stable version) so we have this fix: https://github.com/vuejs/vue-loader/commit/f79bb087f9211c3ea19d63c1dcfd758d6dbad095
Cheers!
=> Require vue-loader 15.9.5 to work with Encore 1.0

lib/config-generator.js, test/functional.js
Fixes #931
* `liveReload` currently causes the page to ALWAYS reload: HMR never has a chance to update the content. Disabling by default. This will mean people that currently like the liveReload won't have it anymore unless they re-enable it. But allowing HMR to be broken is not ok. See: https://github.com/symfony/webpack-encore/issues/931#issuecomment-784483725
* The hostname used for the web socket changed in Webpack 4. For most users it doesn't matter... they use localhost everywhere. But this PR explicitly sets the web socket hostname to the hostname of the dev-server.
TODO: fix/add tests
Cheers!
=> fixing 2 issues related to webpack-dev-server and HMR

lib/friendly-errors/formatters/missing-css-file.js, lib/friendly-errors/formatters/missing-loader.js, test/friendly-errors/formatters/missing-css-file.js, test/friendly-errors/formatters/missing-loader.js
As a new user I came across a very confusing error message which took me way too long to debug. I was trying to set up the new webpack-encore configuration to use the `twig-loader`. I followed all the instructions, but I kept getting the following error:
```
./node_modules/twig/twig.js contains a reference to the file path.
This file can not be found, please check it for typos or update it if the file got moved.
```
Since "file path" is a very commonly used phrased, I did not realise that it meant that the file (or dependency) `path` was missing. Searching online also didn't help me out.
I'm not sure what the best solution is (or if it's an accepted edge case), but having it highlighted could save some new users a lot of time and frustration when starting out. I decided on simple quotes …
=> Clarify missing css file error message

test/functional.js
The "highest" tests are passing due to some minor change that's causing the final filename of some split chunks to be different (before `961.js` now `865.js`). This is a meaningless change. This PR will be to allow the asserts to use a dynamic `[id]` in place of the filename.
The actual implementation is still a TODO
=> WIP - fixing tests by allowing dynamic filename asserts

package.json, test/functional.js
Hi!
When I tagged 1.1.2, I mistakenly included 1 commit that was not on main. That commit, plus the commit that bumps `package.json`, were never pushed to main. Thanks to @Kocal for pointing this out - it was an error in my release process. Fortunately, the extra commit was just to a test file.
This PR adds those 2 commits, and reverts the test commit. This add the 2 missing commits into `main` and revert the code change that was never intended.
Cheers!
=> v1.1.2  missing commits from main

lib/config-generator.js
Addresses on issue on #941 
This disallows the "find an open port" feature in webpack-dev-server. This is unfortunate, as this is a nice feature of webpack-dev-server where if port 8080 is open, it will try 8081, etc.
However, because we need to build a manifest.json file, we need to know what
the port is for sure at Webpack config build time. Even going through the same
async process of using the "find-port" package isn't really doable... as it
would make the entire config generation async (this may be possible, but would
change a ton of things in Encore & in userland `webpack.config.js` files).
Cheers!
=> Do not allow webpack-dev-server to find an open port

index.js, test/index.js
Replace #900 by adding a more generic and flexible API than `Encore.isDev()`/`Encore.isProd()`, see https://github.com/symfony/webpack-encore/pull/900#issuecomment-769380187.
`Encore.when()` takes two parameters:
- `condition`: can be a callback (where the current instance of Encore is passed as first parameter) or a boolean. If this results to `true`, the parameter `callback` is called
- `callback`: executed when parameter `condition` results to `true`, it takes the current instance of Encore as first parameter
WDYT? Thanks!
=> feat: add Encore.when()

package.json, yarn.lock
https://github.com/ztoben/assets-webpack-plugin/pull/392 makes our integrity calculation no longer work, as the files have not been emitted by the time processOutput() is called.
A better fix will need to be created. I'll create an issue after merging this for that.
The most obvious would be to - if possible - use the existing https://github.com/ztoben/assets-webpack-plugin#integrity 
If it IS possible (I don't know if it exposes all the same info we do), then we would need to deprecate the current format of the entrypoints.json file in favor of this new one.
=> Locking assets-webpack-plugin to less than 7.1.0

package.json, yarn.lock
This PR resolve the newly published critical security issue [CVE-2021-23369 : Remote code execution in handlebars when compiling templates](https://github.com/advisories/GHSA-f2jv-r9rf-7988)
=> Resolve security issue CVE-2021-23369

.github/workflows/node-windows.yml, .travis.yml, package.json, yarn.lock
I'm not sure what the policy on node compatibility is, but the latest major of `less-loader` only seems to drop Node 10 support ([release notes](https://github.com/webpack-contrib/less-loader/blob/master/CHANGELOG.md)).
Webpack Encore still supports Node 10, but that should still be possible if you use one of the other allowed less loaders.
=> Allow less-loader v9

lib/webpack-manifest-plugin/hooks.js, package.json, run-persistent-tests.js, test/functional.js, test/helpers/setup.js, test/persistent-cache/functional.js
So, the solution for #936 was not complex at all, but creating a failing test was. 
I needed to update the test scripts in the `package.json`, as webpack simply doesn't write it's cache until the mocha  process ends. I did not find an alternative way to trigger the cache files to be written. 
So, I separated the persistent cache tests into a dedicated directory/file, which is ignored during the normal test run. I added commands to run the persistent cache test both with and without previous cache (using the `CLEAR_PERSISTENT_CACHE` environment variable), and updated the original test command to run the normal test once, and the persistent cache tests twice (so the second run is with a valid cache). 
I also needed to update the temp directory generation for the persistent cache, as it need …
=> #936: Fix manifest key problem when using copy files

fixtures/vuejs3-typescript/types/shims-vue.d.ts, package.json, yarn.lock
Like #999, the only breaking change is that the minimum supported version of Node.js is 12.0.0,
see https://github.com/TypeStrong/ts-loader/blob/main/CHANGELOG.md#v900
**EDIT:** PR #1000 :exploding_head: 
**EDIT 2:** Looks like something broke. It happens since 9.0.0 (exact version) but I don't know what happens. 
**EDIT 3:** Added TypeScript types for `.vue`, and it's working fine. Not sure if it's really a BC break, I expect most of people using Vue 3 + TypeScript already using a `vue-shims.d.ts` file... :confused:
=> Allow ts-loader ^9.0.0, close #993

package.json, yarn.lock
Looks like the removed a [less context option](https://github.com/webpack-contrib/less-loader/releases/tag/v10.0.0), but I could find any place where it is used in this package.
=> Allow less-loader 10

lib/config-generator.js, package.json, yarn.lock
Fixes #1017 
But, I would love some real-world testing :). It looks like I had this option in the wrong spot. Or, it was allowed in this spot in an earlier version of 4 beta, but now it has this proper spot.
Cheers!
=> changing position of host option for webpack-dev-server

test/plugins/terser.js
Just a fix in tests for highest versions.
Something in terser-webpack-plugin changed internally, and the terserOptions are stored elsewhere.
=> asserting a different option for terser-webpack-plugin

lib/config/parse-runtime.js, test/config/parse-runtime.js
The --public option used to specify which host to use in the manifest.json.
That options was deprecated in favor of client.webSocketURL
Fixes #1044
=> Fix deprecated public option failure

CHANGELOG.md
just a typo fix
1.7.0 release notes should also be updated
https://github.com/symfony/webpack-encore/releases/tag/v1.7.0
=> changelog: fix typo in dropped typescript version 8 -> 3

package.json, yarn.lock
As per @stof suggestion, I've updated the version constraint to `^4.9.1`
Fixes #1069
=> #1069 Increased webpack-cli version constraint to v.4.9.1

index.js, lib/WebpackConfig.js, lib/config/validator.js, test/WebpackConfig.js, test/config-generator.js
Purpose: I dislike having to call `addEntry` multiple times, and would prefer the cleaner look of a single hash.
Example Usage:
```js
Encore.addEntries({
main: './path/to/main.js',
secondary: './path/to/another/file.js',
});
```
This supports validation that any keys provided in the Object literal do not yet exist as an Entrypoint or Style Entrypoint.
Tests have also been updated.
---
Another new method (`validateNameIsNewEntry`) was also added to extract and consolidate logic related to checking for duplicate entrypoint names.
Tests for this other function have also been added.
=> New Encore method for adding multiple entries at once

lib/config-generator.js, test/config-generator.js
Just a rebase of #1056 - probably the failures there were temporary to when that PR was opened.
=> Rebase of avif support

lib/plugins/eslint.js, yarn.lock
This PR fixes #1075 by loading `eslint-plugin` only when it's needed.
Failures are not related.
cc @weaverryan
=> fix: lazy-load ESLint plugin dependency, fix #1075

bin/encore.js, lib/config/parse-runtime.js, test/config/parse-runtime.js
Add --public option like an encore argument to specify public url that use for entry asset in entrypoints.json. 
I have a problem with this suggestion when I try to build webpack but the result is correct.
Anyone can help me ?
Fixes #1094
=> Revert removing public option

lib/plugins/define.js, test/config-generator.js, test/plugins/define.js
Following the warning on https://webpack.js.org/plugins/define-plugin/:
> When defining values for process prefer
> `'process.env.NODE_ENV': JSON.stringify('production')` over
> `process: { env: { NODE_ENV: JSON.stringify('production') } }`.
> Using the latter will overwrite the process object which can break
> compatibility with some modules that expect other values on the
> process object to be defined.
This fixed a conflict warning I had when using [`dotenv-webpack` plugin](https://github.com/mrsteele/dotenv-webpack):
```
DefinePlugin
Conflicting values for 'process.env'
```
=> fix: don't override process variable in DefinePlugin configuration

lib/config-generator.js, test/config-generator.js
With the realease of the version 10 of preact, preact compat was migrated inside preact library removing the need for preact-compat.
https://preactjs.com/guide/v10/switching-to-preact/
=> fix: preact compat

lib/features.js
Allows sass-embedded as additional sass-loader backend ass discussed in #1093 and https://github.com/symfony/webpack-encore/issues/1011#issuecomment-1040041930
=> Adds sass-embedded as possible sass-loader backend (see #1093)

lib/config/parse-runtime.js, test/config/parse-runtime.js
Check also the serverType cli param to define if the devServer is in https mode
=> Use cli param server-type to define devServer https mode

lib/config-generator.js, lib/features.js, lib/utils/get-vue-version.js
https://blog.vuejs.org/posts/vue-2-7-naruto.html
With `vue 2.7` released, so i try to upgrade my app to `vue 2.7`.
and followed the upgrade guide, after I removed the package `vue-template-compiler`
> Upgrade vue to ^2.7.0. You can also remove vue-template-compiler from the dependencies - it is no longer needed in 2.7.
it shows me the error
```
Error: Install vue-template-compiler to use enableVueLoader(  )
yarn add vue-template-compiler --dev
```
so add a special feature named `vue2.7`
=> Add vue 2.7 feature

CHANGELOG.md, test_apps/pnpm-with-babel/README.md, test_apps/pnpm-with-external-babel-config/README.md, test_apps/pnpm/README.md
As asked in https://github.com/symfony/webpack-encore/pull/1150#issuecomment-1240082899.
=> chore: add changelog for 4.0.0

fixtures/js/hello_world.svelte, index.js, lib/WebpackConfig.js, lib/config-generator.js, lib/features.js, package.json, test/WebpackConfig.js, test/functional.js, test/index.js, yarn.lock
> Svelte is a radical new approach to building user interfaces. Whereas traditional frameworks like React and Vue do the bulk of their work in the browser, Svelte shifts that work into a compile step that happens when you build your app. [https://svelte.dev/](https://svelte.dev/)
The goal of this PR is to add support of Svelte to Webpack Encore.
=> add svelte support to webpack encore

package.json, test_apps/yarn-pnp-with-babel/yarn.lock, test_apps/yarn-pnp-with-external-babel-config/yarn.lock, test_apps/yarn-pnp/yarn.lock
Fixes https://github.com/symfony/webpack-encore/issues/1165
=> Match `@vue/compiler-sfc` requirement with `vue`

package.json
Following issue #1172 
In `package.json` : updated webpack-cli peerDependencies and reordered svelte in devDependencies
=> chore: updated webpack-cli peerDependencies with v5

index.js
The encore config wrapper does not have an optional/default argument fallback for `enableBabelTypeScriptPreset` and thus creates an invalid number of arguments notice when used without any while it does allow it in https://github.com/symfony/webpack-encore/blob/2e044a958dae6e6820aa99706642039ef8dd27cd/lib/WebpackConfig.js#L729
=> Added default fallback value for `enableBabelTypeScriptPreset`

lib/WebpackConfig.js
There is a duplicate } sign. So this is printed in the error message.
=> Fix typo in error message

lib/plugins/eslint.js
Hi!
This finishes #1155.
Cheers!
=> Delay force sync until needed

.github/workflows/high-depends.yml, .github/workflows/lint.yaml, .github/workflows/low-depends.yml, .github/workflows/stable-tests.yml, .github/workflows/testing_apps.yml
This will avoid using deprecated versions
=> Update the versions for official actions

package.json
Bump Vulnerability from dependencies YAML, after 'yarn audit'
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ moderate      │ Uncaught Exception in yaml                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ yaml                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.2.2                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @symfony/webpack-encore                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path …
=> upgrade css-minimizer-webpack-plugin to fix vulnerability YAML

package.json, yarn.lock
Bumps babel-loader from 8.2.5 to 9.1.2
This fixes a prototype pollution vulnerability addressed in [babel-loader](https://github.com/babel/babel-loader/pull/980)
**Dependencies updates**
- Bump qs from 6.5.2 to 6.5.3 by https://github.com/dependabot in https://github.com/babel/babel-loader/pull/977
- Bump json5 from 2.2.1 to 2.2.3 by https://github.com/dependabot in https://github.com/babel/babel-loader/pull/980
=> Bump babel-loader from 8.2.5 to 9.1.2

README.md
Related to https://github.com/symfony/demo/pull/1449#pullrequestreview-1727404666
=> docs: document asset mapper and remove demo link

lib/config/validator.js, test/config/validator.js
i have a multi config setup. In one of my configs i only call `addPlugin()`.
```js
const path = require('node:path');
const fileName = process.env.COPY_FILE_NAME || false;
let copyConfig = {};
if (fileName) {
copyConfig = {
from: `${fileName}`,
to: `${path.dirname(path.relative(path.resolve(__dirname, 'picture'), fileName))}/[name].[contenthash:8][ext]`,
}
} else {
copyConfig = {
from: './picture',
to: '[path][name].[contenthash:8][ext]'
}
Encore.cleanupOutputBeforeBuild()
};
const CopyPlugin = require('copy-webpack-plugin');
Encore
...
.addPlugin(
new CopyPlugin({
patterns: [copyConfig],
})
)
...
```
this config only copy files optional only  a specific ;)
Actually only use `addPlugin()` is not supported. I change the code and add test for the scenario.
releated #1140
=> bug: accept use with addPlugin only

.github/workflows/high-depends.yml, .github/workflows/lint.yaml, .github/workflows/low-depends.yml, .github/workflows/stable-tests.yml, .github/workflows/testing_apps.yml, CHANGELOG.md, fixtures/css/autoprefixer_test.css, package.json, test/functional.js, yarn.lock
Node 16 and 18 have reached their end of life.
=> Bumping Node minimum to 20

.github/workflows/high-depends.yml, .github/workflows/low-depends.yml, .github/workflows/stable-tests.yml, package.json, yarn.lock
Removing Node 18 support was an accident - https://github.com/symfony/webpack-encore/pull/1254#issuecomment-1910589709 - so let's fix that :)
=> Re-adding node 18 support

package.json, yarn.lock
We have some vulnerability alerts raised by Dependabot https://github.com/symfony/webpack-encore/security/dependabot?q=is%3Aopen+manifest%3Ayarn.lock
The PR won't impact the end users, they probably already updated the dependencies themselves, it's only some maintenance... :)
The following dependencies are updated to their patched version:
- `braces`
- `webpack-dev-middleware`
- `express`
- `follow-redirects`
The following dependencies are **not updated**, as it requires major updates that can break user-land:
- `ws`, used by `webpack-dev-server` (need one major update)
- `@adobe/css-tools`, used by `stylus` (needs **three** major updates)
- `tough-cookie` and `request`, used by the archived package `zombie`, there are no new releases, so we must find a replacment
- …
=> Update some dev-dependencies to fix vulnerability issues

lib/WebpackConfig.js
Close #1281 
Let's deprecate it for now, and remove it later in a new major version
=> Deprecate ESLint integration

lib/plugins/eslint.js
While working on ESLint deprecation (requiring me to have a valid setup, etc...), those messages are displayed when you try to enable ESLint integration:
```
➜  sf-webpack-encore-lab git:(main) ✗ pnpm dev
> @ dev /Users/kocal/workspace/sf-webpack-encore-lab
> encore dev
Running webpack ...
DEPRECATION  The ESLint integration is now deprecated and will be removed in the next major release. Please use the standalone ESLint CLI instead, or use the ESLint Webpack plugin directly.
Error: No ESLint configuration has been found.
FIX  Run command ./node_modules/.bin/eslint --init or manually create a .eslintrc.js file at   the root of your project.
If you prefer to create a .eslintrc.js file by yourself, here is an example to get you started:
// .eslintrc.js
module.exports = {
parser: …
```
=> Improve ESLint and Babel help messages, when enabling ESLint integration

CHANGELOG.md, fixtures/vuejs-jsx/main_v3.js, lib/WebpackConfig.js, lib/features.js, lib/loaders/babel.js, package.json, test/functional.js, yarn.lock
Close #1277, follow #553 from 5 years ago :D 
Adding JSX support to Vue 3 is possible through the Babel plugin `@vue/babel-plugin-jsx` (https://github.com/vuejs/babel-plugin-jsx).
Here is a demo on my _lab project_, with Vue 3 and JSX enabled:
https://github.com/user-attachments/assets/4a28f122-a357-4586-ba60-e92f496aa523
--- 
I've also fixed the changelog's last entries
=> Add JSX support for Vue 3

CHANGELOG.md, lib/config-generator.js
Close #1276, Vue 2 has reached its end of life the 31st december 2023.
If I install `vue@2` or if I specify `version: 2` in `.enableVueLoader()`, a deprecation message is now shown:
=> Deprecate Vue 2 support

CHANGELOG.md, lib/EncoreProxy.js, package.json, yarn.lock
Package [`fast-levenshtein`](https://www.npmjs.com/package/fast-levenshtein) is a wrapper around [`fastest-levenshtein`](https://www.npmjs.com/package/fastest-levenshtein), but we do not need locale-sensitive string comparaison.
```
Package size report
===================
Package info for "@symfony/webpack-encore@4.6.1": 61 MB
Released: 2024-01-25 17:18:00.95 +0000 UTC (30w1d ago)
Downloads last week: 48,107 (32.02%)
Estimated traffic last week: 2.9 TB
Subdependencies: 634
Removed dependencies:
- fast-levenshtein@3.0.0: 30 kB (0.04%)
Downloads last week: 1,563,771 (N/A% from 3.0.0)
Downloads last week from "@symfony/webpack-encore@4.6.1": 48,107 (N/A%)
Traffic last week: N/A
Traffic from "@symfony/webpack-encore@4.6.1": 2.9 TB (N/A%)
Subdependencies: 1 (0.15%)
Added dependencies:
+ …
```
=> Replace `fast-levenshtein` by `fastest-levenshtein`

CHANGELOG.md, lib/config/parse-runtime.js, lib/utils/package-up.js, package.json, test/utils/package-up.js, yarn.lock
[`pkg-up`](https://www.npmjs.com/package/pkg-up) is deprecated, and has been replaced by [`package-up`](https://www.npmjs.com/package/package-up). This one is more lightweight, but is only available as ESM format, which is not compatible with Encore.
So, I've dropped `pkg-up` and inlined `package-up` and its single dependency [`find-up-simple`](https://www.npmjs.com/package/find-up-simple), with some tests. 
Removing `pkg-up` remove a lot of sub-dependencies aswell, which is better in term of security, but also in term of bandwidth and size on disk. 
Here, you can see the impact without `pkg-up` and with `package-up`,  we reduce the bandwidth consumption by ~500 GB (but note that our inlined solution is smaller than `package-up`): 
```
Package size report
===================
Package info …
```
=> Replace `pkg-up` by an inlined solution

CHANGELOG.md, package.json, test_apps/npm-with-babel/package-lock.json, test_apps/npm-with-babel/package.json, test_apps/npm-with-external-babel-config/package-lock.json, test_apps/npm-with-external-babel-config/package.json, test_apps/npm/package-lock.json, test_apps/npm/package.json, test_apps/pnpm-with-babel/package.json, test_apps/pnpm-with-babel/pnpm-lock.yaml, test_apps/pnpm-with-external-babel-config/package.json, test_apps/pnpm-with-external-babel-config/pnpm-lock.yaml, test_apps/pnpm/package.json, test_apps/pnpm/pnpm-lock.yaml, test_apps/yarn-pnp-with-babel/package.json, test_apps/yarn-pnp-with-babel/yarn.lock, test_apps/yarn-pnp-with-external-babel-config/package.json, test_apps/yarn-pnp-with-external-babel-config/yarn.lock, test_apps/yarn-pnp/package.json, test_apps/yarn-pnp/yarn.lock, yarn.lock
=> Drop `webpack-cli` 4 support, only `webpack-cli` ^5.1.4 is supported

CHANGELOG.md, lib/config-generator.js, lib/features.js, lib/friendly-errors/transformers/missing-loader.js, lib/utils/get-vue-version.js, package.json, test/config-generator.js, test/functional.js, test/utils/get-vue-version.js, yarn.lock
Close #1283.
Vue 2 reached its end of life months ago, let's remove it for the next major version of Encore.
It also allows us to close #1272.
=> Drop Vue 2 support (End-Of-Life), only Vue 3 is supported

.github/workflows/testing_apps.yml, package.json, test_apps/pnpm-with-babel/package.json, test_apps/pnpm-with-external-babel-config/package.json, test_apps/pnpm/package.json
This makes it easier for contributors using corepack as their way of installing yarn (which is the recommended way nowadays)
=> Update the package.json to specify the yarn version for corepack

index.js, lib/WebpackConfig.js, lib/config-generator.js, lib/config/path-util.js, lib/config/validator.js, lib/loaders/babel.js, lib/loaders/css-extract.js, lib/loaders/css.js, lib/loaders/handlebars.js, lib/loaders/less.js, lib/loaders/sass.js, lib/loaders/stylus.js, lib/loaders/typescript.js, lib/loaders/vue.js, lib/plugins/asset-output-display.js, lib/plugins/clean.js, lib/plugins/define.js, lib/plugins/delete-unused-entries.js, lib/plugins/entry-files-manifest.js, lib/plugins/forked-ts-types.js, lib/plugins/friendly-errors.js, lib/plugins/manifest.js, lib/plugins/mini-css-extract.js, lib/plugins/notifier.js, lib/plugins/optimize-css-assets.js, lib/plugins/terser.js, lib/plugins/variable-provider.js, lib/plugins/vue.js, lib/utils/get-vue-version.js, lib/utils/manifest-key-prefix-helper.js
This is better when the import was added only to make the type available in JSDoc types.
=> Use JSDoc imports instead of unused runtime imports

.github/workflows/high-depends.yml, .github/workflows/low-depends.yml, .github/workflows/stable-tests.yml, CHANGELOG.md, package.json
Due to the `>=18.0.0` version constraint in `engines.node`, it means that we allows Node.js 19 and 21, but, we don't want that.
Odds versions are supported only 6 months, it only helps library maintainers to update their library comptability with a new Node.js LTS-version. You can see on https://nodejs.org/fr/about/previous-releases that Node.js 19 is not present and Node.js 21 support has been stopped around ~may 2024.
Some of our dependencies explicitly does not support explicitly Node.js 19/21, like css-minimizer-webpack-plugin that [I've tried to upgrade to v5](https://github.com/symfony/webpack-encore/actions/runs/10654621974/job/29531168804?pr=1320):
```
yarn install v1.22.22
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error cssnano@7.0.5: …
```
=> Drop support for Node.js 19 and 21

CHANGELOG.md, package.json, yarn.lock
Replace #1320
It also upgrade cssnano to ^7, see https://github.com/webpack-contrib/css-minimizer-webpack-plugin/blob/master/CHANGELOG.md#700-2024-05-07
Node.js support has been updated to ^18.12
=> Drop css-minimizer-webpack-plugin 5 support, only css-minimizer-webpack-plugin 7 is supported

CHANGELOG.md, package.json, yarn.lock
Close #1290 
Upgrade webpack-dev-server didn't have impact for Encore itself, but it can be the case for end-users.
After upgrading webpack-dev-server to ^5.0, my project that use the following devServer configuration is still working as expected:
```js
Encore.configureDevServerOptions((options) => {
options.allowedHosts = 'all';
options.client = {
overlay: false, // hidden overlay: multiple errors caused by third-party scripts
};
options.server = {
type: 'https',
options: {
pfx: path.join(process.env.HOME, '.symfony5/certs/default.p12'),
},
};
})
```
=> Drop support of webpack-dev-server ^4.8, add support for webpack-dev-server ^5.0

index.js, lib/WebpackConfig.js, lib/config-generator.js, lib/utils/apply-options-callback.js, lib/utils/package-up.js
These are the type improvements coming from my investigation in #816 (and then pushed until the end rather than stopping at a few methods for the experiment)
=> Add more precise types in the JSDoc

lib/config-generator.js
webpack-dev-server supports providing a string when only the type needs to be configured. Our code checking the type to detect the usage of `https` was not properly handling such configuration.
=> Fix compat with configuring the devserver server as a string

lib/config-generator.js, lib/loaders/css.js
This will allow type-checking the codebase, by fixing cases where the typescript inference is not sufficient without a hint.
=> Add some types in the internal implementation of Encore

lib/WebpackConfig.js
Buffers can implicitly be converted to string (implicitly using `utf8` as encoding) but the type checker does not like this kind of implicit conversion.
When passing an encoding to `fs.readFileSync`, it returns a string by performing an explicit conversion using the provided encoding.
=> Read the controllers.json as string rather than Buffer

.eslintrc.js, .github/workflows/lint.yaml, .github/workflows/testing_apps.yml, package.json, test/functional.js, test/helpers/assert.js, test/helpers/setup.js, yarn.lock
https://github.com/assaf/zombie is archived since december 2023, and its last release is from 4 years ago.
I've replaced it by https://github.com/puppeteer/puppeteer, a modern and maintained API to run and test code in a **real browser** (zombie used `jsdom`). I had to adapt `requestTestPage` to pass the browser as first argument, because I want to launch the browser **only a single time** (in `before()`).
=> test(deps): replace Zombie by Puppeteer

package.json, test/functional.js
This configures our CI to enforce fixing ESLint warnings and not just errors.
The only warning that was reported (since #1331) is solved by simplifying the code (removing the function that was keeping a closure on the `browser` mutable variable)
=> Fix ESLint warning

lib/features.js, package.json, yarn.lock
This also removes the optional peerDependency on stylus that was using an outdated range because Encore does not actually use stylus in any way but only stylus-loader. And stylus-loader already declares a required peerDependency on stylus, making package managers ensure its presence when stylus-loader is present.
=> Upgrade the version of stylus used in dev

.github/workflows/low-depends.yml, CHANGELOG.md, bin/encore.js, index.js, lib/WebpackConfig.js, lib/features.js, package.json, test/bin/encore.js
As discussed with @stof, we want to make the webpack-dev-server an optional peer dependency:
JavaScript dependencies are problematic, depending on many sub-dependencies, which in turn depend on more sub-dependencies, and so on... Welcome to the dependency hell!
Even if the dev-server functionality isn't used, the dependency tree is immensely more complex (over 300 additional dependencies), but this is an open door to security holes present in “discrete” (say “little-known”), but over-used dependencies.
In recent months, a sort of “witch-hunt” has been set up by some people in the JavaScript ecosystem, to replace sub-dependencies with lighter alternatives (either another dependency, or a native version) in _popular project_. I've started doing this on Encore for a few dependencies, and …
=> Make webpack-dev-server optional

CHANGELOG.md, lib/plugins/entry-files-manifest.js, lib/plugins/plugin-priorities.js, lib/webpack/entry-points-plugin.js, package.json, yarn.lock
| Issues        | Fix #969 
This PR replaces the https://github.com/ztoben/assets-webpack-plugin dependency with an internal plugin, this allows us:
- to drop a dependency, and simplify the code (we don't need 10 ~options to generate the `entrypoints.json` for the WebpackEncoreBundle)
- to not depend on https://github.com/waysact/webpack-subresource-integrity, which is necessary to use the `integrity` options of https://github.com/ztoben/assets-webpack-plugin
- to generate the integrity data **after** files have been emitted
**Things done in this PR:**
- Re-implement https://github.com/ztoben/assets-webpack-plugin functionality as closely as possible
- Ensure …
=> Replace `assets-webpack-plugin` dependency by an internal plugin, to generate `entrypoints.json` file

CHANGELOG.md, fixtures/preact-css-modules/components/App.jsx, fixtures/react-css-modules/components/App.jsx, fixtures/vuejs-jsx/components/Hello.jsx, package.json, test/functional.js, yarn.lock
Let's continue to upgrade major dependencies, see https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md#700-2024-04-04 for changelog
=> Drop support of css-loader ^6, add support for css-loader ^7.1

CHANGELOG.md, index.js, lib/WebpackConfig.js, lib/loaders/babel.js, test/WebpackConfig.js, test/loaders/babel.js
=> Add options configuration callback to Encore.enableReactPreset()

CHANGELOG.md, lib/webpack/entry-points-plugin.js, test/functional.js
=> Add support for integrity hashes when asset names contain a query string

CHANGELOG.md
| Bug fix?      | yes/no
| New feature?  | yes/no 
| Deprecations? | yes/no 
=> chore: Rewrite changelog for 5.0.0

CHANGELOG.md, lib/webpack/entry-points-plugin.js, test/functional.js
| Bug fix?      | yes
| New feature?  | no 
When working on https://github.com/symfony/webpack-encore-bundle/pull/237, I haven't able to see integrity hashes added on `<link>` tags, because my project uses query-string in generated filenames, but the bundle was not able to get those integrity hashes (because the `entrypoints.json` file contained  `"/build/sentry.js": "sha384-hash"` instead of `"/build/sentry.js?v=b86ff72e": "sha384-hash"`)
=> Fix issue between `Encore.enableIntegrityHashes()` and filenames with a query-string

.github/workflows/high-depends.yml, .github/workflows/low-depends.yml, .github/workflows/stable-tests.yml
| New feature?  | no 
See https://github.com/actions/runner-images/issues/12045
=> [CI] Upgrade deprecated os windows-2019 to windows-latest
